---
sidebar: sidebar 
permalink: access-data.html 
keywords: access data, mount point, mount volumes, mount clients, on-premises 
summary: Puoi accedere ai file system FSX per ONTAP da on-premise montando i volumi per i client NAS e montando le LUN iSCSI per i client SAN. 
---
= Accedi ai dati del file system FSX per ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puoi accedere ai file system FSX per ONTAP da on-premise montando i volumi per i client NAS e montando le LUN iSCSI per i client SAN.

link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/supported-fsx-clients.html["Accesso ai dati"^] Nella documentazione di Amazon FSX per NetApp ONTAP vengono forniti argomenti su come accedere ai dati per riferimento.

È anche possibile ottenere il punto di montaggio per i volumi in NetApp Workload Factory.



== Ottieni il punto di montaggio per i volumi in NetApp Workload Factory

Ottenere il punto di montaggio per un volume per montare una condivisione su un client CIFS share o NFS.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system con il volume e quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda Volumi, seleziona il menu azioni per il volume, quindi *Azioni di base* e infine *Visualizza comando di montaggio*.
. Nella finestra di dialogo del comando Mount, selezionare *Copy* (Copia) per copiare il comando per il punto di montaggio NFS o la condivisione CIFS. Immettere il comando copiato nel terminale.
. Selezionare *Chiudi*.




== Connettersi a client NAS

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-linux-client.html["Montare un volume sui client Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-windows-client.html["Montare un volume sui client Windows"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-mac-client.html["Montare un volume sui client macOS"^]




== Connettersi a client SAN

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-luns-linux.html["Montare un LUN iSCSI su client Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-windows.html["Montare un LUN iSCSI sui client Windows"^]

