---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: Replica dei volumi di data Protection o la replica dei dati dei volumi a cascata, per estendere la data Protection ai sistemi terziari o per migrare i dati. 
---
= Replica i volumi di data Protection in una fabbrica di workload BlueXP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Replica dei volumi di data Protection o la replica dei dati dei volumi a cascata, per estendere la data Protection ai sistemi terziari o per migrare i dati.

.A proposito di questa attività
BlueXP  workload Factory supporta la replica dei volumi di protezione dei dati, chiamati anche _Cascade Deployments_. Una distribuzione _a cascata_ è costituita da una catena di relazioni in cui viene eseguito il mirroring di un volume di origine in un volume secondario (primo hop) e il volume secondario in un terzo volume (secondo hop). Se il volume secondario non è più disponibile, è possibile sincronizzare la relazione tra il volume primario e il volume terzo senza eseguire un nuovo trasferimento di riferimento.

Questa funzione è supportata per i file system FSX per ONTAP con ONTAP versione 9,6 e successive. Fare riferimento alla link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["Documentazione ONTAP per le versioni compatibili di ONTAP"^].

Ulteriori informazioni su link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work["come funzionano le distribuzioni a cascata"^].

.Prima di iniziare
Prima di iniziare, prendere in considerazione quanto segue:

* I volumi che fanno parte di una configurazione a cascata possono richiedere più tempo per la risincronizzazione.
* Se il volume di origine della relazione è un volume di protezione dei dati ed è una destinazione di un'altra relazione, l'inversione della relazione di replica non è supportata.
* È supportata una replica di un volume di data Protection (o un secondo hop). Non è considerata la Best practice creare una seconda replica di un volume di protezione dati (o un terzo hop).


.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system che contiene i volumi da replicare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Nella tabella volumi, selezionare uno o più volumi di protezione dati (volumi DP/replicati), quindi selezionare *Replica dati*.
. Nella pagina Replica dati, in destinazione replica, fornire quanto segue:
+
.. *FSX per il file system ONTAP*: Selezionare credenziali, area e FSX per il nome del file system ONTAP per il file system FSX per ONTAP di destinazione.
.. *Nome VM di archiviazione*: Selezionare la VM di archiviazione dal menu a discesa.
.. *Volume name*: Il nome del volume di destinazione viene generato automaticamente con il seguente formato `{OriginalVolumeName}_copy`. È possibile utilizzare il nome del volume generato automaticamente o immettere un altro nome di volume.
.. *Caso di utilizzo*: Selezionare uno dei seguenti casi di utilizzo per la replica. In base al caso di utilizzo selezionato, il modulo viene compilato in fabbrica dal carico di lavoro con i valori consigliati, conformemente alle Best practice. È possibile accettare i valori consigliati o apportare modifiche durante la compilazione del modulo.
+
*** Migrazione: Trasferimento dei dati nel file system FSX per ONTAP di destinazione
*** Disaster recovery "hot": Garantisce alta disponibilità e rapido disaster recovery per i carichi di lavoro critici
*** Disaster recovery a freddo o di archivio:
+
**** Disaster recovery a freddo: Utilizza RTO (recovery time objective) e RPO (recovery point objects) più lunghi per ridurre i costi
**** Archiviazione: Replica i dati per storage e conformità a lungo termine


*** Altro


.. *Criterio di tiering*: Selezionare il criterio di tiering per i dati memorizzati nel volume di destinazione. Il criterio di tiering predefinito corrisponde alla policy di tiering consigliata per il caso d'utilizzo selezionato.
+
_Balanced (Auto)_ è la policy di tiering predefinita quando si crea un volume utilizzando la console workload Factory. Per ulteriori informazioni sulle policy di tiering dei volumi, fare riferimento a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacità di storage dei volumi"^] nella documentazione di AWS FSX per NetApp ONTAP. Nota: Workload Factory utilizza nomi basati su casi d'utilizzo nella console workload Factory per le policy di tiering e include i nomi delle policy di tiering di FSX per ONTAP tra parentesi.

+
Se hai selezionato il caso di utilizzo della migrazione, il workload in fabbrica sceglie automaticamente di copiare la policy di tiering del volume di origine nel volume di destinazione. Puoi deselezionare questa casella per copiare la policy di tiering e selezionare una policy di tiering che si applica al volume selezionato per la replica.

.. *Velocità di trasferimento massima*: Selezionare *limitata* e immettere il limite massimo di trasferimento in MB/s. In alternativa, selezionare *illimitato*.
+
Senza limiti, le prestazioni della rete e delle applicazioni potrebbero diminuire. In alternativa, consigliamo una velocità di trasferimento illimitata per i file system FSX per ONTAP per i carichi di lavoro critici, ad esempio quelli utilizzati principalmente per il disaster recovery.



. In Impostazioni di replica, specificare quanto segue:
+
.. *Intervallo di replica*: Consente di selezionare la frequenza di trasferimento degli snapshot dal volume di origine al volume di destinazione.
.. *Conservazione a lungo termine*: Facoltativamente, abilitare gli snapshot per la conservazione a lungo termine. La conservazione a lungo termine permette ai servizi di business di continuare a funzionare anche in caso di guasto completo del sito, supportando il failover delle applicazioni in modo trasparente utilizzando una copia secondaria.
+
Le repliche senza conservazione a lungo termine utilizzano la policy _MirrorAllSnapshots_. Abilitando la conservazione a lungo termine, alla replica viene assegnata la policy _MirrorAndVault_.

+
Se si attiva la conservazione a lungo termine, selezionare un criterio esistente o creare un nuovo criterio per definire gli snapshot da replicare e il numero da conservare.

+

NOTE: Per la conservazione a lungo termine sono necessarie etichette di origine e destinazione corrispondenti. Se lo si desidera, workload Factory può creare etichette mancanti.

+
*** *Scegliere un criterio esistente*: Selezionare un criterio esistente dal menu a discesa.
*** *Creare una nuova policy*: Fornire quanto segue:
+
**** *Policy name*: Inserire un nome di policy.
**** Opzionale: Attiva gli snapshot immutabili.
+
***** Selezionare *attiva istantanee immutabili* per impedire l'eliminazione degli snapshot creati in questo criterio durante il periodo di conservazione.
***** Impostare *periodo di conservazione* in numero di ore, giorni, mesi o anni.


**** *Snapshot policies*: Nella tabella, selezionare la frequenza del criterio di snapshot e il numero di copie da conservare. È possibile selezionare più criteri di snapshot.






. Selezionare *Crea*.


.Risultato
Il volume o i volumi replicati vengono replicati e visualizzati nella scheda *Relazioni di replica* nel file system FSX for ONTAP di destinazione.
