---
sidebar: sidebar 
permalink: change-replication-schedule.html 
keywords: change replication schedule, update replication schedule, edit replication schedule 
summary: Modificare la pianificazione della replica del volume di origine in una relazione di replica in NetApp Workload Factory. 
---
= Consente di modificare la pianificazione della replica di un volume di origine
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Modificare la pianificazione della replica del volume di origine in una relazione di replica in NetApp Workload Factory.

Scegli la frequenza con cui le snapshot dal volume di origine vengono trasferite al volume replicato per soddisfare i tuoi RPO (Point Objective) richiesti.

Quando un cluster ONTAP on-premise è la destinazione della relazione di replica, la modifica della pianificazione della replica non è supportata.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Relazioni di replica*.
. Nella scheda Relazioni di replica, selezionare l'azione della pianificazione delle relazioni di replica da modificare.
. Selezionare *Modifica intervallo di replica*.
. Nella finestra di dialogo Modifica intervallo di replica, selezionare la frequenza di trasferimento dello snapshot dal volume di origine. È possibile scegliere tra le seguenti frequenze:
+
** Ogni 5 minuti
** Ogni ora
** Ogni 8 ore
** Ogni giorno
** Settimanale


. Selezionare *Applica*.

