---
sidebar: sidebar 
permalink: change-replication-schedule.html 
keywords: change replication schedule, update replication schedule, edit replication schedule 
summary: Modifica del piano di replica del volume di origine in una relazione di replica in una fabbrica di workload BlueXP . 
---
= Consente di modificare la pianificazione della replica di un volume di origine
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Modifica del piano di replica del volume di origine in una relazione di replica in una fabbrica di workload BlueXP .

Scegli la frequenza con cui le snapshot dal volume di origine vengono trasferite al volume replicato per soddisfare i tuoi RPO (Point Objective) richiesti.

Quando un cluster ONTAP on-premise è la destinazione della relazione di replica, la modifica della pianificazione della replica non è supportata.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, seleziona il menu a tre punti del file system da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Relazioni di replica*.
. Nella scheda Relazioni di replica, selezionare il menu a tre punti della pianificazione delle relazioni di replica da modificare.
. Selezionare *Modifica intervallo di replica*.
. Nella finestra di dialogo Modifica intervallo di replica, selezionare la frequenza di trasferimento dello snapshot dal volume di origine. È possibile scegliere tra le seguenti frequenze:
+
** Ogni 5 minuti
** Ogni ora
** Ogni 8 ore
** Ogni giorno
** Settimanale


. Selezionare *Applica*.

