---
sidebar: sidebar 
permalink: change-snapshot-policy.html 
keywords: snapshot policy, snapshot schedule, modify snapshot policy, edit snapshot policy, change snapshot policy 
summary: Consente di aggiornare in qualsiasi momento la policy Snapshot di un volume in fabbrica con carichi di lavoro BlueXP . 
---
= Modifica della policy Snapshot di un volume in una fabbrica di workload BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aggiorna la frequenza delle snapshot acquisite per un volume o disattiva le snapshot automatiche in qualsiasi momento nella workload factory di BlueXP .

.Prima di iniziare
Per visualizzare i criteri degli snapshot esistenti, è necessario associare un collegamento. Per associare un collegamento, selezionare *collegamento associato* in *Nome account*. Quindi tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system FSX per ONTAP che contiene il volume con il criterio snapshot da aggiornare, quindi selezionare *Gestisci*.
. Dalla scheda Panoramica del file system, selezionare la scheda *volumi*.
. Selezionare la scheda *volumi*.
. Nella scheda *volumi*, selezionare il menu a tre punti del volume per cui modificare il criterio snapshot.
. Selezionare *azioni protezione dati*, *istantanee*, quindi *Gestisci criteri snapshot*.
. Nella pagina di gestione dei criteri di istantanea, selezionare *Modifica di un criterio di istantanea esistente*.
. Nel campo *Nome criterio snapshot*, selezionare un criterio snapshot diverso per questo volume.
+
Per disattivare le istantanee automatiche, selezionare `none`.

+
Se non esistono altri criteri di snapshot, link:create-snapshot-policy.html["creare un nuovo criterio snapshot per questo volume"].

. Selezionare *Applica* per salvare le modifiche.

