---
sidebar: sidebar 
permalink: change-tiering-policy.html 
keywords: tiering policy, change tier, change tiers, tier policy update 
summary: Modificare la policy di suddivisione in livelli in NetApp Workload Factory per riallocare i dati dal livello di storage primario ad alte prestazioni al livello di storage del pool di capacità secondario. 
---
= Modificare la politica di suddivisione in livelli di un volume in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In NetApp Workload Factory è possibile modificare la policy di suddivisione in livelli per riallocare automaticamente i dati dal livello di storage primario ad alte prestazioni al livello di storage del pool di capacità secondario.

.A proposito di questa attività
È possibile modificare in qualsiasi momento la policy di tiering di un volume. La policy di tiering viene definita per volume.

Decidere dove archiviare i dati ha implicazioni per i risparmi sui costi.

FSX per ONTAP dispone di due Tier per la memorizzazione dei dati dei volumi:

* *Tier di storage SSD*: Questo Tier di storage primario è per i dati a cui si accede più frequentemente, noti anche come dati _hot_. La memorizzazione dei dati nel Tier di storage primario è più costosa rispetto a quella del Tier di storage secondario.
* *Tier di storage del pool di capacità*: Questo Tier di storage secondario è destinato ai dati archiviati o ai dati a cui si accede raramente, noti anche come dati _cold_.


Per ulteriori informazioni sui Tier di storage, fai riferimento link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers["Gestione della capacità di storage"^] alla documentazione in AWS for FSX for NetApp ONTAP.

.Prima di iniziare
Prima di modificare la policy di tiering, rivedere le policy disponibili.

* *Balanced (Auto)*: Criterio di tiering predefinito quando si crea un volume utilizzando l'interfaccia utente. Mantiene i dati ad accesso frequente nel Tier di storage SSD ed esegue il tiering di dati e Snapshot con accesso meno frequente al Tier di storage del pool di capacità dopo il periodo di raffreddamento. Consigliato per carichi di lavoro primari generali.
* *Ottimizzazione dei costi (tutto)*: Esegue il tiering di tutti gli snapshot e i dati nel Tier di storage del pool di capacità. Consigliato per obiettivi secondari.
* *Performance Optimized (solo Snapshot)*: Esegue il tiering solo dei dati snapshot nel Tier di storage del pool di capacità. Consigliato per carichi di lavoro a bassa latenza come database mission-critical.
* *Nessuno*: Mantiene i dati del volume nel Tier di storage SSD, impedendone lo spostamento nel Tier di storage del pool di capacità.


Tenere presente che alcune policy di tiering dispongono di un periodo di raffreddamento minimo associato che imposta il tempo, o _giorni di raffreddamento_, che i dati dell'utente in un volume devono rimanere inattivi per essere considerati "cold" e spostati nel Tier di storage del pool di capacità. Il periodo di raffreddamento inizia quando i dati vengono scritti sul disco.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system con il volume da aggiornare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda Volumi, seleziona il menu delle azioni del volume per cui vuoi modificare la politica di suddivisione in livelli.
. Selezionare *azioni avanzate*, quindi *Modifica criterio di tiering*.
. Nella pagina Change tiering policy (Modifica policy di tiering), selezionare per copiare la policy di tiering del volume di origine o selezionare una delle seguenti policy di tiering:
+
** *Bilanciato (Auto)*: Immettere il numero di giorni di raffreddamento.
** *Costi ottimizzati (tutti)*
** *Ottimizzazione delle prestazioni (solo istantanee)*: Immettere il numero di giorni di raffreddamento.
** *Nessuno*


. Selezionare *Applica*.

