---
sidebar: sidebar 
permalink: clone-volume.html 
keywords: clone volume, clone, clone data 
summary: Clonare un volume in NetApp Workload Factory per creare un volume di lettura/scrittura del volume originale per i test. 
---
= Clonare un volume in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Clonare un volume in NetApp Workload Factory per creare un volume di lettura/scrittura del volume originale per i test.

Il clone riflette lo stato corrente dei dati point-in-time. È inoltre possibile utilizzare i cloni per fornire agli utenti aggiuntivi l'accesso ai dati senza fornire loro l'accesso ai dati di produzione.

.A proposito di questa attività
Il cloning dei volumi è supportato solo per i volumi FlexClone.

Quando viene clonato un volume, viene creato un volume scrivibile con riferimenti agli snapshot dal volume principale. La creazione dei cloni avviene in pochi secondi. I dati clonati non risiedono nel clone del volume, ma risiedono invece nel volume principale. Tutti i nuovi dati scritti sul volume dopo la creazione del clone risiedono sul clone.

Perché un volume clonato contenga tutti i dati del volume principale ed eventuali nuovi dati aggiunti al clone dopo la creazione, sarà necessario link:split-cloned-volume.html["dividere il clone"] farlo dal volume principale. Inoltre, non puoi eliminare un volume principale se ha un clone. Prima di eliminare un volume principale, è necessario dividere un clone.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu azioni del file system FSx for ONTAP che contiene il volume da clonare, quindi seleziona *Gestisci*.
. Dalla scheda Panoramica del file system, selezionare la scheda *volumi*.
. Nella scheda Volumi, seleziona il menu delle azioni del volume da clonare.
. Selezionare *azioni protezione dati*, quindi *Clona volume*.
. Nella finestra di dialogo Clone volume (Clona volume), immettere un nome per il clone del volume.
. Selezionare *Clone*.

