---
sidebar: sidebar 
permalink: configure-active-directory.html 
keywords: configure AD, configure active directory, update ad, edit active directory 
summary: Configurare e aggiornare Active Directory per una VM di archiviazione in un file system FSx for ONTAP in NetApp Workload Factory. 
---
= Configurazione e aggiornamento di Active Directory per una macchina virtuale di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Configurare e aggiornare Active Directory per una VM di archiviazione in un file system FSx for ONTAP in NetApp Workload Factory.

.A proposito di questa attività
La stessa procedura si applica alla configurazione e all'aggiornamento di Active Directory per una VM di storage.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system con la VM di archiviazione da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Dalla scheda VM di archiviazione, selezionare il menu delle azioni della VM di archiviazione per cui configurare Active Directory.
. Selezionare *Gestisci configurazione ad*.
. Nella pagina Gestione configurazione ad, specificare quanto segue:
+
.. *Dominio Active Directory a cui collegarsi*: Immettere il nome di dominio completo (FQDN) di Active Directory.
.. *Indirizzi IP DNS*: Immettere un massimo di tre indirizzi IP separati da virgole.
.. *SMB server NetBIOS name*: Immettere il nome NetBIOS del server SMB dell'oggetto computer Active Directory da creare per la macchina virtuale di storage. Nome della SVM in Active Directory.
.. *Nome utente*: Immettere il nome utente dell'account del servizio nell'Active Directory esistente.
+
Non includere un prefisso o un suffisso di dominio. Per `EXAMPLE\ADMIN`, utilizzare `ADMIN`.

.. *Password*: Immettere la password per l'account del servizio.
.. *Unità organizzativa (OU)*: Immettere l'unità organizzativa.
+
L'unità organizzativa è il nome del percorso distinto dell'unità organizzativa a cui si desidera unire il file system.

.. *Gruppo di amministratori delegati*: Se si desidera, immettere il gruppo di amministratori del file system delegato.
+
Il gruppo di amministratori delegati è il nome del gruppo in Active Directory che può amministrare il file system.

+
Se utilizzi ad Microsoft gestito da AWS, devi specificare un gruppo come ad esempio gli amministratori FSX delegati di AWS, gli amministratori delegati di AWS o un gruppo personalizzato con autorizzazioni delegate all'unità organizzativa.

+
Se si sta effettuando la connessione a un ad gestito autonomamente, utilizzare il nome del gruppo nell'ad. Il gruppo predefinito è `Domain Admins`.



. Selezionare *Applica*.

