---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory analizza regolarmente le configurazioni del file system Amazon FSx for NetApp ONTAP per determinare se ci sono problemi. 
---
= Analisi della configurazione di FSX per i file system ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory analizza regolarmente le configurazioni del file system Amazon FSx for NetApp ONTAP per determinare se ci sono problemi.  Quando vengono rilevati problemi, Workload Factory ti mostra quali sono e ti spiega cosa è necessario modificare per garantire che l'archiviazione del file system raggiunga le massime prestazioni, la massima efficienza dei costi e la conformità alle best practice.

Le funzionalità principali includono:

* Analisi quotidiana della configurazione
* Convalida automatica delle Best practice
* Osservabilità proattiva
* Informazioni sull'azione
* Framework Advisor di AWS con architettura ottimale




== Stato ben progettato

Nella console Workload Factory a livello di file system, lo stato di buona architettura è elencato per tutti i file system FSx for ONTAP .  Gli stati ben progettati sono classificati come "problemi", "non analizzati" o "ben progettati".  Selezionando lo stato ben progettato si viene reindirizzati alla scheda dello stato ben progettato all'interno del file system, dove è possibile trovare il punteggio ben progettato, le categorie di configurazione e tutte le configurazioni per il file system.

Punteggio ben strutturato:: Il punteggio include tutte le configurazioni attualmente analizzate e viene visualizzato come percentuale. Un punteggio del 25% indica che il 25% delle configurazioni del file system è caratterizzato da un'architettura ottimale.
Categorie di configurazione:: Le configurazioni del file system sono organizzate in categorie allineate con i seguenti cinque pilastri del framework ben strutturato AWS.
+
--
* _Reliability_: Garantisce che i carichi di lavoro svolgano le funzioni previste in modo corretto e coerente, anche in presenza di interruzioni. Un esempio di configurazione è FSX per i backup ONTAP.
* _Sicurezza_: Sottolinea la protezione di dati, sistemi e risorse attraverso valutazioni dei rischi e strategie di mitigazione.
* _Eccellenza operativa_: Si concentra sulla fornitura dell'architettura e del valore di business ottimali.
* _Ottimizzazione dei costi_: Mira a fornire valore aziendale riducendo al minimo i costi.
* _Performance Efficiency_: Si concentra sull'utilizzo efficiente delle risorse per soddisfare i requisiti di sistema e mantenere prestazioni ottimali con il variare delle esigenze.


--




== Requisiti di analisi

Per un'analisi completa del file system, è necessario associare un collegamento.  La connettività dei link consente a Workload Factory di analizzare tutte le configurazioni del file system, come la protezione dei dati e le prestazioni.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"].

.Cosa succederà
link:improve-configurations.html["Implementa configurazioni del file system con un'architettura ottimale"]
