---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: Crea una snapshot manuale di un volume FSX per ONTAP in una workload factory BlueXP . Gli snapshot sono versioni point-in-time dei contenuti del tuo volume. 
---
= Crea una snapshot manuale di un volume FSX per ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crea una snapshot manuale di un volume FSX per ONTAP in una workload factory BlueXP . Gli snapshot sono versioni point-in-time dei contenuti del tuo volume.

Gli snapshot sono risorse di volumi e offrono acquisizioni istantanee dei dati che occupano spazio solo per i dati modificati. A causa del cambiamento dei dati nel tempo, le snapshot solitamente occupano più spazio man mano che diventano più datate.

FSX per ONTAP Volumes usa il copy-on-write just-in-time in modo che i file non modificati nelle snapshot non consumino la capacità del volume.


NOTE: Le snapshot non sono copie dei tuoi dati. Se vuoi creare copie dei tuoi dati, prendi in considerazione l'utilizzo di FSX per ONTAP o delle funzionalità di replica dei volumi.

.Prima di iniziare
Per creare uno snapshot manuale di un volume è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. In *archiviazione*, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system che contiene il volume per cui creare uno snapshot, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda *volumi*, selezionare il menu a tre punti per il volume da proteggere con le istantanee.
. Selezionare *azioni protezione dati*, *istantanee*, quindi *Crea un'istantanea*.
. Nella finestra di dialogo Crea un'istantanea, immettere il nome di un'istantanea nel campo *Nome istantanea*.
. Facoltativo: Rendere immutabile lo snapshot per evitare che venga eliminato durante il periodo di conservazione.
+
.. Attiva *istantanee immutabili*.
.. Impostare *periodo di conservazione* come numero di ore, giorni, mesi o anni.
.. Accettare la dichiarazione relativa agli snapshot immutabili.


. Selezionare *Crea*.


.Risultato
Il volume dispone di una copia snapshot.
