---
sidebar: sidebar 
permalink: create-backup.html 
keywords: create backup, volume backup, back up a volume 
summary: Creare un backup manuale di un volume al di fuori dei backup pianificati regolarmente. 
---
= Creare un backup manuale di un volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Creare un backup manuale di un volume al di fuori dei backup pianificati regolarmente.

.A proposito di questa attività
I backup di FSX per ONTAP vengono eseguiti per volume, pertanto ogni backup contiene solo i dati di un volume specifico.

I backup di FSX per ONTAP sono incrementali e questo significa che solo i dati sul volume modificati dopo il salvataggio dell'ultimo backup. In questo modo si riduce al minimo il tempo necessario per creare il backup e lo storage necessario per il backup, risparmiando sui costi di storage senza duplicare i dati.

.Prima di iniziare
Per eseguire il backup dei volumi, sia il volume che il file system devono disporre di una capacità di storage SSD sufficiente per archiviare lo snapshot di backup. Quando si crea una snapshot di backup, la capacità di storage aggiuntiva consumata dalla snapshot non può far sì che il volume superi il 98% di utilizzo dello storage SSD. In questo caso, il backup non viene eseguito correttamente.

.Fasi
. Accedere a. link:https://console.workloads.netapp.com/["Console di workload Factory"^]
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, fare clic sul menu dei tre punti del file system con il volume, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Nella scheda *volumi*, fare clic sul menu dei tre punti per il volume da sottoporre a backup.
. Selezionare *azioni protezione dati*, *FSX per il backup ONTAP*, quindi *Backup manuale*.
. Nella finestra di dialogo Backup manuale, immettere un nome per il backup.
. Fare clic su *Backup*.

