---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: Crea un criterio di snapshot personalizzato per una VM di archiviazione in Workload Factory. 
---
= Creare un criterio di snapshot per le VM di archiviazione in Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crea un criterio di snapshot personalizzato per le VM di archiviazione in Workload Factory per gestire la creazione e la conservazione degli snapshot. Un criterio di snapshot definisce il modo in cui il sistema crea snapshot per una VM di archiviazione. È possibile creare un criterio di snapshot per una VM di archiviazione in un file system FSx for ONTAP . È anche possibile condividere la policy su più VM di archiviazione.

.A proposito di questa attività
È possibile creare un criterio di snapshot personalizzato diverso da quello delle tre policy integrate per FSX for ONTAP:

* `default`
* `default-1weekly`
* `none`


Per impostazione predefinita, ogni volume è associato al criterio di snapshot del file system `default` . Consigliamo di utilizzare questa policy per la maggior parte dei carichi di lavoro.

La personalizzazione di un criterio consente di specificare quando creare le snapshot, il numero di copie da conservare e il nome delle stesse.

.Prima di iniziare
* Una volta creato un criterio snapshot, la sua associazione con le VM di storage non può essere modificata, ma è sempre possibile aggiungere o rimuovere il criterio dai volumi.
* Prima di utilizzare le snapshot, occorre valutare quanto segue:
+
** Per la maggior parte dei set di dati, è sufficiente una capacità aggiuntiva del 20% per conservare le snapshot per un massimo di quattro settimane. Man mano che i dati diventano più datati, il loro utilizzo per i ripristini diventa meno probabile.
** La sovrascrittura di tutti i dati di uno snapshot consuma una notevole capacità del volume, fattore che influisce sul provisioning della capacità del volume.


* Per creare un criterio di snapshot personalizzato, è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.


.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system con il volume e quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Dalla scheda *VM di archiviazione*, seleziona il menu delle azioni per il volume da proteggere con snapshot pianificati, quindi *Azioni avanzate* e infine *Gestisci criteri snapshot*.
. Nella pagina di gestione dei criteri di snapshot, selezionare *Crea criterio di snapshot*.
. Nel campo *Snapshot policy name* (Nome criterio istantanea), immettere un nome per il criterio snapshot.
. Facoltativamente, immettere una descrizione per il criterio snapshot.
. In *Policy Schedule and Copies*, selezionare quando creare snapshot. Ad esempio, ogni minuto o ogni ora.
+
È possibile selezionare più di una frequenza.

. In *numero di copie*, immettere il numero di copie da conservare.
+
Il numero massimo di copie è 1.023.

. Facoltativo: In *convenzione di denominazione*, immettere un *prefisso* per la policy.
. *Etichetta di conservazione* viene compilata automaticamente.
+
Questa etichetta si riferisce all'etichetta SnapMirror o di replica utilizzata per selezionare solo gli snapshot specificati per la replica dal file system di origine a quello di destinazione.

. Facoltativo: Abilitare *istantanee immutabili* per qualsiasi pianificazione necessaria, impostare il *periodo di conservazione* per ogni pianificazione e accettare l'istruzione per continuare.
+
L'attivazione degli snapshot immutabili blocca tutti gli snapshot in questa policy per impedire l'eliminazione degli snapshot durante il periodo di conservazione.

. *Condivisione tra VM di archiviazione*: Abilitata per impostazione predefinita. Quando abilitata, la policy di snapshot viene condivisa tra tutte le macchine virtuali storage nel file system. Disattiva per creare una policy di snapshot per una singola macchina virtuale di storage.
. Selezionare *Crea*.

