---
sidebar: sidebar 
permalink: create-storage-vm.html 
keywords: create storage VM, create svm 
summary: 'È possibile creare una VM di archiviazione FSx per ONTAP (SVM) per fornire servizi di archiviazione e dati per i carichi di lavoro in NetApp Workload Factory.' 
---
= Crea una macchina virtuale di storage per un file system FSX per ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crea una VM di archiviazione (SVM) per un file system FSx for ONTAP per accedere virtualmente ai servizi di archiviazione e dati per i tuoi carichi di lavoro in NetApp Workload Factory.

.A proposito di questa attività
Le VM di archiviazione sono file server isolati che puoi utilizzare per accedere ai dati di ciascun carico di lavoro in Workload Factory Storage.  Ogni SVM ha le proprie credenziali amministrative e i propri endpoint per amministrare e accedere ai dati.

Grazie alle SVM, quando accedi ai dati in FSX per ONTAP, client e workstation montano un volume, una CIFS/SMB share o una LUN iSCSI ospitata da una SVM utilizzando l'endpoint (indirizzo IP) della SVM.

.Prima di iniziare
Verifica del numero supportato di VM storage per file system. Fare riferimento a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Gestione di FSX per ONTAP Storage Virtual Machine"^] nella documentazione AWS per il numero massimo di SVM per file system.



== Creare una VM di storage

È possibile creare una VM di archiviazione dalla console Workload Factory.  Puoi anche utilizzare i seguenti strumenti disponibili in Codebox: REST API, CloudFormation e Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Scopri come utilizzare Codebox per l'automazione"^] .


NOTE: Quando si utilizza Terraform da Codebox, il codice che si copia o si scarica nasconde `fsxadmin` e `vsadmin` password. Sarà necessario immettere nuovamente le password quando si esegue il codice.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system per cui creare una VM di archiviazione e seleziona *Crea una VM di archiviazione*.
. Nella pagina Storage VM, in Storage VM Configuration (Configurazione Storage VM), fornire quanto segue:
+
.. *Nome*: Immettere un nome per la VM di archiviazione.
.. *Credenziali VM di archiviazione*: Fornire una password per l'utente di questa VM di archiviazione o utilizzare le credenziali utente del `vsadmin` file system `fsxadmin` .
.. *Stile di protezione del volume root*: Selezionare lo stile di protezione del volume root a seconda del tipo di client che accedono ai dati: UNIX (client Linux), NTFS (client Windows) o Mixed.
.. *Tags*: Opzionalmente, è possibile aggiungere fino a 50 tag.


. Selezionare *Crea*.

