---
sidebar: sidebar 
permalink: create-file-system.html 
keywords: create, FSx file system, ONTAP file system, Workload Factory, storage 
summary: Utilizzando NetApp Workload Factory è possibile creare un file system FSx per ONTAP per aggiungere e gestire volumi e servizi dati aggiuntivi. 
---
= Creare un file system FSx per ONTAP in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Utilizzando NetApp Workload Factory è possibile creare file system FSx for ONTAP di prima e seconda generazione per aggiungere e gestire volumi e servizi dati aggiuntivi.

.A proposito di questa attività
Durante la creazione del file system vengono create una macchina virtuale di storage e un gruppo di sicurezza.

.Prima di iniziare
Prima di creare il file system FSX per ONTAP, hai bisogno di:

* Credenziali con autorizzazioni di _creazione ed eliminazione del file system_ per creare un file system FSx per ONTAP . link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Scopri come concedere autorizzazioni a un account AWS"^].
* Le informazioni relative all'area geografica e alla VPC per la creazione dell'istanza FSX per ONTAP.




== Crea un file system FSX per ONTAP

È possibile creare un file system FSX per ONTAP utilizzando _creazione rapida_ o _creazione avanzata_. È inoltre possibile utilizzare i seguenti strumenti disponibili in Codebox: API REST, CloudFormation e Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Scopri come utilizzare Codebox per l'automazione"^].


NOTE: Quando si utilizza Terraform da Codebox, il codice che si copia o si scarica nasconde `fsxadmin` e `vsadmin` password. Sarà necessario immettere nuovamente le password quando si esegue il codice.

[role="tabbed-block"]
====
.Creazione rapida
--
Creazione rapida consente di utilizzare una configurazione di Best practice consigliata. È possibile modificare la maggior parte delle impostazioni dopo aver creato un file system FSX per ONTAP.

I file system FSx per ONTAP di seconda generazione rappresentano il tipo di distribuzione predefinito per la creazione rapida, a meno che la regione selezionata non supporti i file system FSx per ONTAP di seconda generazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Crea FSx per ONTAP*.
. Nella pagina Crea FSX per ONTAP, selezionare *creazione rapida*.
+
È anche possibile caricare una configurazione salvata.

. In Configurazione generale del file system, fornire quanto segue:
+
.. *Credenziali AWS*: seleziona per aggiungere le credenziali AWS in Workload Factory o continuare senza credenziali.
.. *Nome file system*: Immettere un nome per il file system.
.. *Regione e VPC*: Selezionare la regione e il VPC per il file system.
.. *Tipo di distribuzione*: Selezionare un tipo di distribuzione.
+
*** Implementazione con zona di disponibilità singola (Single-AZ): Garantisce la disponibilità monitorando gli errori dell'hardware e sostituendo automaticamente i componenti dell'infrastruttura in caso di guasto. Ottiene una durata elevata replicando automaticamente i dati all'interno di una zona di disponibilità per proteggerli dai guasti dei componenti.
+
Questa configurazione è consigliata per carichi di lavoro ad alte prestazioni o quando i carichi di lavoro iniziano con dimensioni ridotte e aumentano progressivamente fino a 72 GB/s di throughput e 2,4 milioni di IOPS.

*** Implementazione di diverse zone di disponibilità (Multi-AZ): Fornisce disponibilità continua ai dati anche quando una zona di disponibilità non è disponibile. Un file system Multi-AZ è progettato per carichi di lavoro di produzione business-critical che richiedono alta disponibilità per i dati dei file ONTAP condivisi e uno storage necessario con replica integrata tra zone di disponibilità.
+
Questa configurazione con coppia HA singola è consigliata per carichi di lavoro che richiedono fino a 6 GB/s di throughput o 200.000 IOPS.



.. *Tags*: Opzionalmente, è possibile aggiungere fino a 50 tag.


. In *Dettagli file system*, specificare quanto segue:
+
.. *Capacità di archiviazione SSD*: Immettere la capacità di archiviazione e selezionare l'unità della capacità di archiviazione.
+
*** Nelle distribuzioni di prima generazione non è possibile ridurre la capacità dopo la creazione del file system.
*** Per le distribuzioni di seconda generazione, è possibile aumentare la capacità dopo la creazione del file system.


.. *Credenziali ONTAP*: Facoltativo. Inserire il nome utente e la password ONTAP. La password può essere impostata ora o in un secondo momento.
+
Se l'utente fornito non è l'utente fsxadmin, e in seguito è necessario reimpostare la password fsxadmin, sarà possibile farlo dalla console AWS.

.. *Impostazione SMB/CIFS*: Opzionale. Se si intende utilizzare il protocollo SMB/CIFS per accedere ai volumi, è necessario configurare Active Directory per la VM di storage durante la creazione del file system. Fornire i seguenti dettagli per la VM di storage creata per questo file system.
+
... *Dominio Active Directory a cui collegarsi*: Immettere il nome di dominio completo (FQDN) per Active Directory.
... *Indirizzi IP DNS*: Immettere un massimo di tre indirizzi IP DNS separati da virgole.
... *SMB server NetBIOS name*: Immettere il nome NetBIOS del server SMB dell'oggetto computer Active Directory da creare per la macchina virtuale di storage. Nome della VM di storage in Active Directory.
... *Nome utente*: Immettere il nome utente dell'account del servizio nell'Active Directory esistente.
+
Non includere un prefisso o un suffisso di dominio. Per `EXAMPLE\ADMIN`, utilizzare `ADMIN`.

... *Password*: Immettere la password per l'account del servizio.
... *Unità organizzativa*: Se si desidera, immettere il nome dell'unità organizzativa in cui si intende creare l'account del computer per FSX per ONTAP. L'unità organizzativa è il nome del percorso distinto dell'unità organizzativa a cui si desidera unire il file system.
... *Gruppo amministratori delegati*: Se si desidera, immettere il nome del gruppo in Active Directory che può amministrare il file system.
+
Se utilizzi ad Microsoft gestito da AWS, devi specificare un gruppo come ad esempio gli amministratori FSX delegati di AWS, gli amministratori delegati di AWS o un gruppo personalizzato con autorizzazioni delegate all'unità organizzativa.

+
Se si sta effettuando l'accesso a un ad autogestito, utilizzare il nome del gruppo nell'ad. Il gruppo predefinito è `Domain Admins`.





. Aprire il *Riepilogo* per esaminare la configurazione definita. Se necessario, è possibile modificare qualsiasi impostazione in questo momento prima di salvare o creare il file system.
. Salvare o creare il file system.


Se è stato creato il file system, è ora possibile visualizzare il file system FSX per ONTAP nella pagina *inventario*.

--
.Creazione avanzata
--
Con creazione avanzata, è possibile impostare tutte le opzioni di configurazione, inclusi disponibilità, protezione, backup e manutenzione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Crea FSx per ONTAP*.
. Nella pagina Crea FSX per ONTAP, selezionare *creazione avanzata*.
+
È anche possibile caricare una configurazione salvata.

. In Configurazione generale del file system, fornire quanto segue:
+
.. *Credenziali AWS*: seleziona per aggiungere le credenziali AWS in Workload Factory o continuare senza credenziali.
.. *Nome file system*: Immettere un nome per il file system.
.. *Regione e VPC*: Selezionare la regione e il VPC per il file system.
.. *Tipo di distribuzione*: seleziona un tipo di distribuzione e una generazione di file system. La disponibilità di un file system di seconda generazione dipende dalla regione selezionata. Se la regione selezionata non supporta i file system FSx for ONTAP di seconda generazione, il tipo di distribuzione passa alla prima generazione.
+
*** Implementazione con zona di disponibilità singola (Single-AZ): Garantisce la disponibilità monitorando gli errori dell'hardware e sostituendo automaticamente i componenti dell'infrastruttura in caso di guasto. Ottiene una durata elevata replicando automaticamente i dati all'interno di una zona di disponibilità per proteggerli dai guasti dei componenti.
+
*Generazione del file system*: Selezionare una delle seguenti opzioni:

+
**** *Seconda generazione*: questa configurazione è consigliata per carichi di lavoro ad alte prestazioni o quando i carichi di lavoro iniziano con dimensioni ridotte e aumentano progressivamente fino a 72 GB/s di throughput e 2,4 milioni di IOPS.
**** *Prima generazione*: questa configurazione è ideale per carichi di lavoro che richiedono fino a 4 GB/s o 160.000 IOPS. I file system di prima generazione possono solo aumentare la capacità.


*** Implementazione di diverse zone di disponibilità (Multi-AZ): Fornisce disponibilità continua ai dati anche quando una zona di disponibilità non è disponibile. Un file system Multi-AZ è progettato per carichi di lavoro di produzione business-critical che richiedono alta disponibilità per i dati dei file ONTAP condivisi e uno storage necessario con replica integrata tra zone di disponibilità.
+
*Generazione del file system*: Selezionare una delle seguenti opzioni:

+
**** *Seconda generazione*: questa configurazione a singola coppia HA è consigliata per carichi di lavoro che richiedono fino a 6 GB/s di throughput o 200.000 IOPS. In un file system Multi-AZ e di seconda generazione, la capacità può aumentare o diminuire in base alle esigenze del carico di lavoro.
**** *Prima generazione*: questa configurazione è ideale per carichi di lavoro che richiedono fino a 4 GB/s o 160.000 IOPS. I file system di prima generazione possono solo aumentare la capacità.




.. *Tags*: Opzionalmente, è possibile aggiungere fino a 50 tag.


. In Dettagli file system, fornire quanto segue:
+
.. *Capacità di archiviazione SSD*: Immettere la capacità di archiviazione e selezionare l'unità della capacità di archiviazione.
+
*** Nelle distribuzioni di prima generazione non è possibile ridurre la capacità dopo la creazione del file system.
*** Per le distribuzioni di seconda generazione, è possibile regolare la capacità.


.. *Capacità di throughput per coppia HA*: seleziona la capacità di throughput per numero di coppie HA. I file system di prima generazione supportano solo una coppia HA.
.. *IOPS forniti*: seleziona una delle seguenti opzioni:
+
*** *Automatico*: per l'impostazione automatica, per ogni GiB creato vengono aggiunti 3 IOPS.
*** *Provisioning da parte dell'utente*: per il provisioning da parte dell'utente, immettere il valore IOPS.


.. *Credenziali ONTAP*: Facoltativo. Inserire il nome utente e la password ONTAP. La password può essere impostata ora o in un secondo momento.
+
Se l'utente fornito non è l'utente fsxadmin, e in seguito è necessario reimpostare la password fsxadmin, sarà possibile farlo dalla console AWS.

.. *Credenziali VM di archiviazione*: Opzionale. Immettere il proprio nome utente. La password può essere specifica per questo file system o è possibile utilizzare la stessa password immessa per le credenziali ONTAP. La password può essere impostata ora o in un secondo momento.
.. *Impostazione SMB/CIFS*: Opzionale. Se si intende utilizzare il protocollo SMB/CIFS per accedere ai volumi, è necessario configurare Active Directory per la VM di storage durante la creazione del file system. Fornire i seguenti dettagli per la VM di storage creata per questo file system.
+
... *Dominio Active Directory a cui collegarsi*: Immettere il nome di dominio completo (FQDN) per Active Directory.
... *Indirizzi IP DNS*: Immettere un massimo di tre indirizzi IP DNS separati da virgole.
... *SMB server NetBIOS name*: Immettere il nome NetBIOS del server SMB dell'oggetto computer Active Directory da creare per la macchina virtuale di storage. Nome della VM di storage in Active Directory.
... *Nome utente*: Immettere il nome utente dell'account del servizio nell'Active Directory esistente.
+
Non includere un prefisso o un suffisso di dominio. Per `EXAMPLE\ADMIN`, utilizzare `ADMIN`.

... *Password*: Immettere la password per l'account del servizio.
... *Unità organizzativa*: Se si desidera, immettere il nome dell'unità organizzativa in cui si intende creare l'account del computer per FSX per ONTAP. L'unità organizzativa è il nome del percorso distinto dell'unità organizzativa a cui si desidera unire il file system.
... *Gruppo amministratori delegati*: Se si desidera, immettere il nome del gruppo in Active Directory che può amministrare il file system.
+
Se utilizzi ad Microsoft gestito da AWS, devi specificare un gruppo come ad esempio gli amministratori FSX delegati di AWS, gli amministratori delegati di AWS o un gruppo personalizzato con autorizzazioni delegate all'unità organizzativa.

+
Se si sta effettuando l'accesso a un ad autogestito, utilizzare il nome del gruppo nell'ad. Il gruppo predefinito è `Domain Admins`.





. In rete e sicurezza, fornire quanto segue:
+
.. *Gruppo di protezione*: Consente di creare o utilizzare un gruppo di protezione esistente.
+
Per un nuovo gruppo di protezione, fare riferimento alla <<Dettagli del gruppo di protezione,dettagli del gruppo di protezione>> per una descrizione dei protocolli, delle porte e dei ruoli del gruppo di protezione.

.. *Zone di disponibilità*: Selezionare zone di disponibilità e subnet.
+
*** Per il nodo di configurazione del cluster 1: Selezionare una zona di disponibilità e una subnet.
*** Per il nodo di configurazione del cluster 2: Selezionare una zona di disponibilità e una subnet.


.. *Tabelle di routing VPC*: Selezionare la tabella di routing VPC per abilitare l'accesso client ai volumi.
.. *Intervallo di indirizzi IP endpoint*: Selezionare *intervallo di indirizzi IP mobili al di fuori del VPC* o *immettere un intervallo di indirizzi IP* e immettere un intervallo di indirizzi IP.
.. *Crittografia*: Selezionare il nome della chiave di crittografia dal menu a discesa.


. In Backup e manutenzione, fornire quanto segue:
+
.. *FSX per il backup ONTAP*: I backup automatici giornalieri sono abilitati per impostazione predefinita. Disattivare se desiderato.
+
... *Periodo conservazione backup automatico*: Immettere il numero di giorni per la conservazione dei backup automatici.
... *Finestra di backup automatico giornaliero*: Selezionare *Nessuna preferenza* (l'ora di inizio del backup giornaliero è selezionata per l'utente) o *selezionare l'ora di inizio per i backup giornalieri* e specificare l'ora di inizio.


.. *Finestra manutenzione settimanale*: Selezionare *Nessuna preferenza* (l'ora di inizio della finestra di manutenzione settimanale è selezionata) o *selezionare l'ora di inizio per la finestra manutenzione settimanale di 30 minuti* e specificare un'ora di inizio.


. Salvare o creare il file system.


Se è stato creato il file system, è ora possibile visualizzare il file system FSX per ONTAP nella pagina *inventario*.

--
====


== Dettagli del gruppo di protezione

Nella tabella seguente sono riportati i dettagli dei gruppi di protezione, inclusi protocolli, porte e ruoli.

[]
====
[cols="2,2,4a"]
|===
| Protocollo | Porta | Ruolo 


| SSH | 22  a| 
Accesso SSH all'indirizzo IP della LIF di gestione del cluster o di una LIF di gestione dei nodi



| TCP | 80  a| 
Accesso alla pagina web all'indirizzo IP della LIF di gestione cluster



| TCP/UDP | 111  a| 
Chiamata a procedura remota per NFS



| TCP/UDP | 135  a| 
Chiamata a procedura remota per CIFS



| UDP | 137  a| 
Risoluzione dei nomi NetBIOS per CIFS



| TCP/UDP | 139  a| 
Sessione del servizio NetBIOS per CIFS



| TCP | 443  a| 
Accesso API REST ONTAP all'indirizzo IP della LIF di gestione cluster o di una LIF di gestione SVM



| TCP | 445  a| 
Microsoft SMB/CIFS su TCP con frame NetBIOS



| TCP/UDP | 635  a| 
Montaggio NFS



| TCP | 749  a| 
Kerberos



| TCP/UDP | 2049  a| 
Daemon del server NFS



| TCP | 3260  a| 
Accesso iSCSI tramite LIF dei dati iSCSI



| TCP/UDP | 4045  a| 
Daemon di blocco NFS



| TCP/UDP | 4046  a| 
Network status monitor per NFS



| UDP | 4049  a| 
Protocollo di quota NFS



| TCP | 10000  a| 
Protocollo di gestione dati di rete (NDMP) e comunicazione NetApp SnapMirror intercluster



| TCP | 11104  a| 
Gestione della comunicazione NetApp SnapMirror intercluster



| TCP | 11105  a| 
Trasferimento dei dati SnapMirror con LIF intercluster



| TCP/UDP | 161-162  a| 
Protocollo SNMP (Simple Network Management Protocol)



| Tutti gli ICMP | Tutto  a| 
Eseguire il ping dell'istanza

|===
====
.Cosa succederà
Con un file system nell'inventario di archiviazione, è possibile link:create-volume.html["creare volumi"]gestire il file system FSX per ONTAP e impostare link:data-protection-overview.html["protezione dei dati"] le risorse.
