---
sidebar: sidebar 
permalink: create-link.html 
keywords: links, add, add links, add link, create link 
summary: Puoi creare e gestire i link per fornire una relazione di fiducia e connettività tra un account di fabbrica del carico di lavoro BlueXP  e uno o più file system FSX per ONTAP. 
---
= Creare un collegamento in fabbrica del carico di lavoro BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puoi creare e gestire i link per creare una relazione di fiducia e la connettività tra un account workload Factory e uno o più file system FSX per ONTAP in una workload factory di BlueXP . In questo modo puoi monitorare e gestire determinate funzionalità direttamente dal file system FSX per ONTAP che non sono disponibili tramite l'API AWS FSX per ONTAP.

link:links-overview.html["Ulteriori informazioni sui collegamenti"].

.A proposito di questa attività
I link sfruttano AWS Lambda per eseguire codice in risposta a eventi e gestire automaticamente le risorse di calcolo richieste da tale codice. I link creati fanno parte del tuo account NetApp e sono associati a un account AWS.

È possibile creare un collegamento nell'account quando si definisce un file system FSX per ONTAP. Tale collegamento verrà utilizzato per il file system e da altri file system FSX per ONTAP.

Per creare il link, devi lanciare uno stack AWS CloudFormation nel tuo account AWS.

Sono disponibili due opzioni per la creazione dei collegamenti, automatica o manuale.

* Automaticamente: Crea un collegamento con la registrazione automatica tramite workload Factory. Un collegamento creato automaticamente richiede token per l'automazione della fabbrica del carico di lavoro e il codice CloudFormation ha una durata breve. Può essere utilizzato solo per un massimo di 6 ore.
* Manualmente: Crea un collegamento con la registrazione manuale. Il codice CloudFormation persiste e consente di completare l'operazione con più tempo. Ciò è utile quando si lavora con diversi team, come Security e DevOps, che prima devono concedere le autorizzazioni necessarie per completare la creazione del collegamento.


.Prima di iniziare
* Si consiglia di considerare quale opzione di creazione del collegamento si utilizzerà.
* Devi disporre delle credenziali per accedere al tuo account AWS.
* Quando si aggiunge un collegamento utilizzando uno stack CloudFormation, è necessario disporre delle seguenti autorizzazioni nell'account AWS:
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


[role="tabbed-block"]
====
.Crea automaticamente
--
Utilizzare CloudFormation per creare e registrare automaticamente il collegamento all'interno di workload Factory.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system a cui associare un collegamento, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare *Associa collegamento*.
. Nella finestra di dialogo Associa collegamento, selezionare *Crea un nuovo collegamento* e selezionare *continua*.
. Nella pagina Crea collegamento, fornire quanto segue:
+
.. *Nome collegamento*: Immettere il nome che si desidera utilizzare per questo collegamento. Il nome deve essere univoco all'interno dell'account.
.. *Tag*: Se lo si desidera, aggiungere qualsiasi tag che si desidera associare a questo collegamento in modo da poter categorizzare più facilmente le risorse. Ad esempio, è possibile aggiungere un tag che identifica questo collegamento come utilizzato da FSX per i file system ONTAP.
+
L'account AWS e le informazioni aggiuntive per account, posizione e gruppo sicurezza vengono recuperate automaticamente in base al file system FSX per ONTAP.



. Selezionare *Crea*.
+
Viene visualizzata la finestra di dialogo Redirect to CloudFormation (Reindirizza a CloudFormation) che spiega come creare il collegamento dal servizio AWS CloudFormation.

. Seleziona *continua* per aprire la console di gestione AWS, quindi accedi all'account AWS per questo file system FSX per ONTAP.
. Nella pagina creazione rapida stack, in funzionalità, selezionare *Acknowledge that AWS CloudFormation May create IAM resources* (riconosco che AWS CloudFormation potrebbe creare risorse IAM*).
+
Tenere presente che vengono concesse tre autorizzazioni a Lambda quando si avvia il modello CloudFormation. Workload Factory utilizza queste autorizzazioni quando si utilizzano i collegamenti.

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. Selezionare *Crea pila*, quindi selezionare *continua*.
+
È possibile monitorare lo stato di creazione del collegamento dalla pagina Eventi. Questa operazione non dovrebbe richiedere più di 5 minuti.

. Tornare all'interfaccia della workload Factory e si noterà che il collegamento è associato al file system FSX per ONTAP.


--
.Crea manualmente
--
Con questa opzione, estrai l'ARN per il link da AWS CloudFormation e riportalo qui. Workload Factory registra manualmente il collegamento.

.Fasi
Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^]. . Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*. . Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system a cui associare un collegamento, quindi selezionare *Gestisci*. . Nella panoramica del file system, selezionare *Associa collegamento*. . Nella finestra di dialogo Associa collegamento, selezionare *Crea un nuovo collegamento* e selezionare *continua*. . Nella pagina Crea collegamento, fornire quanto segue: .. *Nome collegamento*: Immettere il nome che si desidera utilizzare per questo collegamento. Il nome deve essere univoco all'interno dell'account. .. *Tag*: Se lo si desidera, aggiungere qualsiasi tag che si desidera associare a questo collegamento in modo da poter categorizzare più facilmente le risorse. Ad esempio, è possibile aggiungere un tag che identifica questo collegamento come utilizzato da FSX per i file system ONTAP. .. *Registrazione link*: Seleziona sulla freccia a discesa per espandere le istruzioni su come registrare il link dal servizio AWS CloudFormation. Seguire le istruzioni.

+ tenere presente che tre autorizzazioni vengono concesse a Lambda quando si avvia il modello CloudFormation. Workload Factory utilizza queste autorizzazioni quando si utilizzano i collegamenti.

+

[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
+ dopo aver creato correttamente lo stack, incollare l'ARN lambda nella casella di testo. .. L'account AWS e le informazioni aggiuntive per account, posizione e gruppo sicurezza vengono recuperate automaticamente in base al file system FSX per ONTAP. . Selezionare *Crea*.

+ è possibile monitorare lo stato di creazione del collegamento dalla pagina Eventi. Questa operazione non dovrebbe richiedere più di 5 minuti. . Tornare all'interfaccia della workload Factory e si noterà che il collegamento è associato al file system FSX per ONTAP.

--
====
.Risultato
Il collegamento creato è associato al file system FSX per ONTAP.
