---
sidebar: sidebar 
permalink: create-replication.html 
keywords: replication, replicate 
summary: Crea una relazione di replica per un file system FSX per ONTAP per evitare la perdita di dati in caso di disastro imprevisto. 
---
= Creazione di un rapporto di replica in una fabbrica di workload BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crea un rapporto di replica per un file system FSX per ONTAP in una fabbrica di workload BlueXP  per evitare la perdita di dati in caso di un disastro imprevisto.

.A proposito di questa attività
La replica rappresenta un livello aggiuntivo di data Protection, essenziale in caso di disastro nella regione in cui risiedono i dati. La perdita di dati può essere evitata se si utilizza la replica tra più aree.

Questa operazione crea una relazione di replica per uno o tutti i volumi di origine in un file system FSX per ONTAP.

I volumi replicati nel file system di destinazione sono volumi di protezione dei dati (DP) e seguono il formato di denominazione: `{OriginalVolumeName}_copy`.

.Prima di iniziare
Prima di iniziare, assicurarsi di soddisfare i seguenti prerequisiti.

* È necessario disporre di due file system disponibili nell'inventario di storage per creare una relazione di replica.
* I due file system utilizzati per la relazione di replica devono disporre di un collegamento associato. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.


Completare i seguenti passaggi per replicare volumi selezionati o replicare tutti i volumi in un file system.

Puoi replicare un volume di origine (lettura/scrittura) o un volume di data Protection (DP). La replica a cascata è supportata, ma non è un terzo hop. Ulteriori informazioni su link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_cascade-replication/cascade-replication.html["replica a cascata"^].

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system che contiene i volumi da replicare, quindi selezionare *Gestisci*.
. Replicare tutti i volumi in un file system o volumi selezionati.
+
** Per replicare tutti i volumi in un file system: Dalla panoramica del file system, selezionare *Replica dati*.
** Per replicare volumi selezionati: Dalla panoramica del file system, selezionare la scheda *volumi*.
+
Nella tabella volumi, selezionare uno o più volumi, quindi selezionare *Replica dati*.



. Nella pagina Replica dati, in destinazione replica, fornire quanto segue:
+
.. *FSX per il file system ONTAP*: Selezionare credenziali, area e FSX per il nome del file system ONTAP per il file system FSX per ONTAP di destinazione.
.. *Nome VM di archiviazione*: Selezionare la VM di archiviazione dal menu a discesa.
.. *Volume name*: Il nome del volume di destinazione viene generato automaticamente con il seguente formato `{OriginalVolumeName}_copy`. È possibile utilizzare il nome del volume generato automaticamente o immettere un altro nome di volume.
.. *Caso di utilizzo*: Selezionare uno dei seguenti casi di utilizzo per la replica. In base al caso di utilizzo selezionato, il modulo viene compilato in fabbrica dal carico di lavoro con i valori consigliati, conformemente alle Best practice. È possibile accettare i valori consigliati o apportare modifiche durante la compilazione del modulo.
+
*** Migrazione: Trasferimento dei dati nel file system FSX per ONTAP di destinazione
*** Disaster recovery "hot": Garantisce alta disponibilità e rapido disaster recovery per i carichi di lavoro critici
*** Disaster recovery a freddo o di archivio:
+
**** Disaster recovery a freddo: Utilizza RTO (recovery time objective) e RPO (recovery point objects) più lunghi per ridurre i costi
**** Archiviazione: Replica i dati per storage e conformità a lungo termine


*** Altro
+
Inoltre, la selezione del caso d'utilizzo determina il criterio di replica o il criterio SnapMirror (ONTAP). I termini utilizzati per descrivere i criteri di replica provengono da link:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["Documentazione di ONTAP 9"^].

+
**** Per la migrazione e altre, il criterio di replica è denominato _MirrorAllSnapshots_. _MirrorAllSnapshots_ è un criterio asincrono per il mirroring di tutti gli snapshot e del file system attivo più recente.
**** Per il disaster recovery hot, cold o di archivio, il criterio di replica si chiama _MirrorAndVault_. _MirrorAndVault_ è un criterio asincrono e vault per il mirroring del file system attivo più recente e degli snapshot giornalieri e settimanali.
+
Per tutti i casi di utilizzo, se si abilitano gli snapshot per la conservazione a lungo termine, il criterio di replica predefinito è _MirrorAndVault_.





.. *Criterio di tiering*: Selezionare il criterio di tiering per i dati memorizzati nel volume di destinazione. Il criterio di tiering predefinito corrisponde alla policy di tiering consigliata per il caso d'utilizzo selezionato.
+
_Balanced (Auto)_ è la policy di tiering predefinita quando si crea un volume utilizzando la console workload Factory. Per ulteriori informazioni sulle policy di tiering dei volumi, fare riferimento a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacità di storage dei volumi"^] nella documentazione di AWS FSX per NetApp ONTAP. Nota: Workload Factory utilizza nomi basati su casi d'utilizzo nella console workload Factory per le policy di tiering e include i nomi delle policy di tiering di FSX per ONTAP tra parentesi.

+
Se hai selezionato il caso di utilizzo della migrazione, il workload in fabbrica sceglie automaticamente di copiare la policy di tiering del volume di origine nel volume di destinazione. Puoi deselezionare questa casella per copiare la policy di tiering e selezionare una policy di tiering che si applica al volume selezionato per la replica.

.. *Velocità di trasferimento massima*: Selezionare *limitata* e immettere il limite massimo di trasferimento in MB/s. In alternativa, selezionare *illimitato*.
+
Senza limiti, le prestazioni della rete e delle applicazioni potrebbero diminuire. In alternativa, consigliamo una velocità di trasferimento illimitata per i file system FSX per ONTAP per i carichi di lavoro critici, ad esempio quelli utilizzati principalmente per il disaster recovery.



. In Impostazioni di replica, specificare quanto segue:
+
.. *Intervallo di replica*: Consente di selezionare la frequenza di trasferimento degli snapshot dal volume di origine al volume di destinazione.
.. *Conservazione a lungo termine*: Facoltativamente, abilitare gli snapshot per la conservazione a lungo termine. La conservazione a lungo termine permette ai servizi di business di continuare a funzionare anche in caso di guasto completo del sito, supportando il failover delle applicazioni in modo trasparente utilizzando una copia secondaria.
+
Le repliche senza conservazione a lungo termine utilizzano la policy _MirrorAllSnapshots_. Abilitando la conservazione a lungo termine, alla replica viene assegnata la policy _MirrorAndVault_.

+
Se si attiva la conservazione a lungo termine, selezionare un criterio esistente o creare un nuovo criterio per definire gli snapshot da replicare e il numero da conservare.

+

NOTE: Per la conservazione a lungo termine sono necessarie etichette di origine e destinazione corrispondenti. Se lo si desidera, workload Factory può creare etichette mancanti.

+
*** *Scegliere un criterio esistente*: Selezionare un criterio esistente dal menu a discesa.
*** *Creare una nuova policy*: Fornire quanto segue:
+
**** *Policy name*: Inserire un nome di policy.
**** Opzionale: Attiva gli snapshot immutabili.
+
***** Selezionare *attiva istantanee immutabili* per impedire l'eliminazione degli snapshot creati in questo criterio durante il periodo di conservazione.
***** Impostare *periodo di conservazione* in numero di ore, giorni, mesi o anni.


**** *Snapshot policies*: Nella tabella, selezionare la frequenza del criterio di snapshot e il numero di copie da conservare. È possibile selezionare più criteri di snapshot.






. Selezionare *Crea*.


.Risultato
La relazione di replica viene visualizzata nella scheda *Relazioni di replica* nel file system FSX for ONTAP di destinazione.
