---
sidebar: sidebar 
permalink: create-link.html 
keywords: connect, connection, link, lambda link, associate link, create link, authenticate link 
summary: Puoi creare e gestire i link per fornire una relazione di fiducia e connettività tra un account di fabbrica del carico di lavoro BlueXP  e uno o più file system FSX per ONTAP. 
---
= Connettersi a un file system FSX per ONTAP con un collegamento Lambda
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Per eseguire operazioni avanzate di gestione di ONTAP, è necessario stabilire la connettività tra l'account di fabbrica del carico di lavoro e uno o più file system FSX per ONTAP. Stabilire la connettività include l'associazione di collegamenti Lambda nuovi ed esistenti e l'autenticazione dei collegamenti. L'associazione di collegamento consente di monitorare e gestire determinate funzioni direttamente dal file system FSX per ONTAP che non sono disponibili tramite l'API AWS FSX per ONTAP.

link:links-overview.html["Ulteriori informazioni sui collegamenti"].

.A proposito di questa attività
I link sfruttano AWS Lambda per eseguire codice in risposta a eventi e gestire automaticamente le risorse di calcolo richieste da tale codice. I link creati fanno parte del tuo account NetApp e sono associati a un account AWS.

È possibile creare un collegamento nell'account quando si definisce un file system FSX per ONTAP. Tale collegamento verrà utilizzato per il file system e da altri file system FSX per ONTAP. È anche possibile associare un collegamento a un file system in un secondo momento.

I collegamenti richiedono l'autenticazione. Puoi creare link autentici utilizzando le credenziali memorizzate nel servizio delle credenziali in fabbrica del workload o con le tue credenziali memorizzate in AWS Secrets Manager. Per ogni collegamento è supportato un solo metodo di autenticazione. Ad esempio, se si seleziona l'autenticazione del collegamento con AWS Secrets Manager, non sarà possibile modificare il metodo di autenticazione in un secondo momento.


NOTE: AWS Secrets Manager non è supportato quando si utilizza un connettore.



== Associare un nuovo collegamento

L'associazione di un nuovo collegamento include la creazione e l'associazione di collegamenti.

Per creare collegamenti in questo flusso di lavoro sono disponibili due opzioni: automaticamente o manualmente. Per creare il link, devi lanciare uno stack AWS CloudFormation nel tuo account AWS.

* Automaticamente: Crea un collegamento con la registrazione automatica tramite workload Factory. Un collegamento creato automaticamente richiede token per l'automazione della fabbrica del carico di lavoro e il codice CloudFormation ha una durata breve. Può essere utilizzato solo per un massimo di sei ore.
* Manualmente: Crea un collegamento con la registrazione manuale. Il codice CloudFormation persiste e consente di completare l'operazione con più tempo. Ciò è utile quando si lavora con team diversi come Security e DevOps, che potrebbero prima dover concedere le autorizzazioni necessarie per completare la creazione del collegamento.


.Prima di iniziare
* Si consiglia di considerare quale opzione di creazione del collegamento si utilizzerà.
* Devi avere almeno un file system FSX per ONTAP in una workload factory. Per scoprire o creare file system FSx per ONTAP, è necessario disporre di un account AWS con autorizzazioni per le istanze FSx per ONTAP e link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html#overview["aggiungere le credenziali in fabbrica del carico di lavoro"^] con autorizzazioni di _sola lettura_ o _lettura/scrittura_ per la gestione dell'archiviazione.
* Per la connettività del collegamento, le seguenti porte devono essere aperte nel gruppo di sicurezza associato al file system FSx per ONTAP.
+
** Per la console della fabbrica del carico di lavoro: porta 443 (HTTPS)
** Per CloudShell: porta 22 (SSH)


* Quando si aggiunge un collegamento utilizzando uno stack CloudFormation, è necessario disporre delle seguenti autorizzazioni nell'account AWS:
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


[role="tabbed-block"]
====
.Crea automaticamente
--
Utilizzare CloudFormation per creare e registrare automaticamente il collegamento all'interno di workload Factory.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system a cui associare un collegamento, quindi selezionare *Associa collegamento*.
. Nella finestra di dialogo Associa collegamento, selezionare *Crea un nuovo collegamento* e selezionare *continua*.
. Nella pagina Crea collegamento, fornire quanto segue:
+
.. *Nome collegamento*: Immettere il nome che si desidera utilizzare per questo collegamento. Il nome deve essere univoco all'interno dell'account.
.. *AWS Secrets Manager*: Facoltativo. Consente alla workload Factory di recuperare le credenziali di accesso a FSX per ONTAP da AWS Secrets Manager.
+
Lo stack di distribuzione dei collegamenti aggiunge il seguente regex ARN del gestore segreto predefinito al criterio di autorizzazione Lambda: `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*`.

+
È possibile creare segreti in allineamento con le autorizzazioni predefinite o assegnare autorizzazioni personalizzate per il criterio di collegamento.

+
*Configurare l'endpoint privato VPC in AWS Secrets Manager* è disattivato per impostazione predefinita. Se si seleziona questa opzione, il segreto viene memorizzato utilizzando l'endpoint privato VPC anziché localmente.

.. *Autorizzazioni collegamento*: seleziona una delle seguenti opzioni per le autorizzazioni collegamento:
+
*** *Automatico*: seleziona questa opzione in modo che il codice AWS CloudFormation crei automaticamente la policy di autorizzazione Lambda e il ruolo di esecuzione.
*** *Fornito dall'utente*: selezionare questa opzione per assegnare un ruolo di esecuzione Lambda specificato e le relative policy associate al collegamento Lambda. Le seguenti autorizzazioni sono richieste per la policy di autorizzazione Lambda .  `secretsmanager:GetSecretValue` l'autorizzazione è richiesta solo se hai abilitato AWS Secrets Manager.
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses",
"secretsmanager:GetSecretValue"
----
+
Immettere l'ARN del ruolo di esecuzione Lambda nella casella di testo.



.. *Tag*: Se lo si desidera, aggiungere qualsiasi tag che si desidera associare a questo collegamento in modo da poter categorizzare più facilmente le risorse. Ad esempio, è possibile aggiungere un tag che identifica questo collegamento come utilizzato da FSX per i file system ONTAP.
+
L'account AWS e le informazioni aggiuntive per account, posizione e gruppo sicurezza vengono recuperate automaticamente in base al file system FSX per ONTAP.



. Selezionare *Crea*.
+
Viene visualizzata la finestra di dialogo Redirect to CloudFormation (Reindirizza a CloudFormation) che spiega come creare il collegamento dal servizio AWS CloudFormation.

. Seleziona *continua* per aprire la console di gestione AWS, quindi accedi all'account AWS per questo file system FSX per ONTAP.
. Nella pagina creazione rapida stack, in funzionalità, selezionare *Acknowledge that AWS CloudFormation May create IAM resources* (riconosco che AWS CloudFormation potrebbe creare risorse IAM*).
+
Tenere presente che vengono concesse tre autorizzazioni a Lambda quando si avvia il modello CloudFormation. Workload Factory utilizza queste autorizzazioni quando si utilizzano i collegamenti.

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. Selezionare *Crea pila*, quindi selezionare *continua*.
+
È possibile monitorare lo stato di creazione del collegamento dalla pagina Eventi. Questa operazione non dovrebbe richiedere più di 5 minuti.

. Tornare all'interfaccia della workload Factory e si noterà che il collegamento è associato al file system FSX per ONTAP.


--
.Crea manualmente
--
Con questa opzione, estrai l'ARN per il link da AWS CloudFormation e riportalo qui. Workload Factory registra manualmente il collegamento.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system a cui associare un collegamento, quindi selezionare *Associa collegamento*.
. Nella finestra di dialogo Associa collegamento, selezionare *Crea un nuovo collegamento* e selezionare *continua*.
. Nella pagina Crea collegamento, fornire quanto segue:
+
.. *Nome collegamento*: Immettere il nome che si desidera utilizzare per questo collegamento. Il nome deve essere univoco all'interno dell'account.
.. *AWS Secrets Manager*: Facoltativo. Consente alla workload Factory di recuperare le credenziali di accesso a FSX per ONTAP da AWS Secrets Manager.
+
Lo stack di distribuzione dei collegamenti aggiunge il seguente regex ARN del gestore segreto predefinito al criterio di autorizzazione Lambda: `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*`.

+
È possibile creare segreti in allineamento con le autorizzazioni predefinite o assegnare autorizzazioni personalizzate per il criterio di collegamento.

+
*Configurare l'endpoint privato VPC in AWS Secrets Manager* è disattivato per impostazione predefinita. Se si seleziona questa opzione, il segreto viene memorizzato utilizzando l'endpoint privato VPC anziché localmente.

.. *Autorizzazioni collegamento*: seleziona una delle seguenti opzioni per le autorizzazioni collegamento:
+
*** *Automatico*: seleziona questa opzione in modo che il codice AWS CloudFormation crei automaticamente la policy di autorizzazione Lambda e il ruolo di esecuzione.
*** *Fornito dall'utente*: selezionare questa opzione per assegnare un ruolo di esecuzione Lambda specificato e le relative policy associate al collegamento Lambda. Le seguenti autorizzazioni sono richieste per la policy di autorizzazione Lambda .  `secretsmanager:GetSecretValue` l'autorizzazione è richiesta solo se hai abilitato AWS Secrets Manager.
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses"
"secretsmanager:GetSecretValue"
----
+
Immettere l'ARN del ruolo di esecuzione Lambda nella casella di testo.



.. *Tag*: Se lo si desidera, aggiungere qualsiasi tag che si desidera associare a questo collegamento in modo da poter categorizzare più facilmente le risorse. Ad esempio, è possibile aggiungere un tag che identifica questo collegamento come utilizzato da FSX per i file system ONTAP.
.. *Registrazione del collegamento*: seleziona la freccia a discesa per espandere le istruzioni su come registrare il collegamento dal servizio AWS CloudFormation o tramite Terraform. Seguire le istruzioni.
+
Tenere presente che vengono concesse tre autorizzazioni a Lambda quando si avvia il modello CloudFormation. Workload Factory utilizza queste autorizzazioni quando si utilizzano i collegamenti.

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
+
Dopo aver creato correttamente lo stack, incollare l'ARN lambda nella casella di testo.

.. L'account AWS e le informazioni aggiuntive per account, posizione e gruppo sicurezza vengono recuperate automaticamente in base al file system FSX per ONTAP.


. Selezionare *Crea*.
+
È possibile monitorare lo stato di creazione del collegamento dalla pagina Eventi. Questa operazione non dovrebbe richiedere più di 5 minuti.

. Tornare all'interfaccia della workload Factory e si noterà che il collegamento è associato al file system FSX per ONTAP.


--
====
.Risultato
Il collegamento creato è associato al file system FSX per ONTAP. È possibile eseguire operazioni ONTAP avanzate.



== Associare un collegamento esistente a un file system FSX per ONTAP

Dopo aver creato un collegamento, associarlo a uno o più file system FSX per ONTAP.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system a cui associare un collegamento, quindi selezionare *Associa collegamento*.
. Nella pagina di collegamento Associa, selezionare *Associa un collegamento esistente*, selezionare il collegamento e selezionare *continua*.
. Selezionare la modalità di autenticazione.
+
** Workload Factory: Immettere la password due volte.
** AWS Secrets Manager: Inserisci il segreto ARN.
+
L'ARN segreto deve includere le seguenti coppie di chiavi valide:

+
*** FilesystemID = FSX_filesystem_id
*** nome utente = FSx_user
*** password = password_utente




. Selezionare *Applica*.


.Risultato
Il collegamento è associato al file system FSX per ONTAP. È possibile eseguire operazioni ONTAP avanzate.



== Risolvere i problemi relativi all'autenticazione del collegamento di AWS Secrets Manager

Problema:: Il collegamento non dispone delle autorizzazioni necessarie per recuperare il segreto.
+
--
*Risoluzione*: Aggiungere le autorizzazioni dopo che il collegamento è attivo. Effettua l'accesso alla console AWS, individua il collegamento Lambda e modifica la policy di autorizzazione allegata.

--
Problema:: Il segreto non è stato trovato.
+
--
*Risoluzione*: Fornire l'ARN segreto corretto.

--
Problema:: Il segreto non è nel formato giusto.
+
--
*Risoluzione*: Vai su AWS Secrets Manager e modifica il formato.

Il segreto deve contenere le seguenti coppie di chiavi valide:

* FilesystemID = FSX_filesystem_id
* nome utente = FSx_user
* password = password_utente


--
Problema:: Il segreto non contiene credenziali ONTAP valide per l'autenticazione del file system.
+
--
*Risoluzione*: Fornire credenziali in grado di autenticare i file system FSX per ONTAP in Gestione segreti AWS.

--

