---
sidebar: sidebar 
permalink: create-backup.html 
keywords: create backup, volume backup, back up a volume 
summary: Creare un backup manuale di un volume in NetApp Workload Factory al di fuori dei backup pianificati regolarmente. 
---
= Creare un backup manuale di un volume in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Creare un backup manuale di un volume al di fuori dei backup pianificati regolarmente in NetApp Workload Factory.

.A proposito di questa attività
I backup di FSX per ONTAP vengono eseguiti per volume, pertanto ogni backup contiene solo i dati di un volume specifico.

I backup di FSX per ONTAP sono incrementali e questo significa che solo i dati sul volume modificati dopo il salvataggio dell'ultimo backup. In questo modo si riduce al minimo il tempo necessario per creare il backup e lo storage necessario per il backup, risparmiando sui costi di storage senza duplicare i dati.

.Prima di iniziare
Per eseguire il backup dei volumi, sia il volume che il file system devono disporre di una capacità di storage SSD sufficiente per archiviare lo snapshot di backup. Quando si crea una snapshot di backup, la capacità di storage aggiuntiva consumata dalla snapshot non può far sì che il volume superi il 98% di utilizzo dello storage SSD. In questo caso, il backup non viene eseguito correttamente.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system con il volume e quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda *Volumi*, selezionare l'azione relativa al volume di cui eseguire il backup.
. Selezionare *azioni protezione dati*, *FSX per il backup ONTAP*, quindi *Backup manuale*.
. Nella finestra di dialogo Backup manuale, immettere un nome per il backup.
. Selezionare *Backup*.

