---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: Dopo aver configurato il file system FSx per ONTAP, creare i volumi FSx per ONTAP nella Workload Factory. 
---
= Creare un volume FSx per ONTAP nella fabbrica del carico di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Dopo aver configurato il file system FSx per ONTAP, crea i volumi FSx per ONTAP nella Workload Factory come risorse virtuali per raggruppare i dati.

.A proposito di questa attività
I volumi FSx per ONTAP raggruppano virtualmente i dati, determinano come vengono archiviati i dati e il tipo di accesso agli stessi. I volumi non consumano capacità di storage del file system. I dati memorizzati in un volume consumano principalmente lo storage SSD. In base alla policy di tiering del volume, i dati potrebbero consumare anche storage pool di capacità. Al momento della creazione, è possibile impostare le dimensioni di un volume e modificarle in un secondo momento.

Per i volumi in uso possono essere utilizzati i seguenti protocolli:

* CIFS: Protocollo di file storage per sistemi operativi Windows
* NFS: Protocollo di file storage per sistemi operativi Unix
* ISCSI: Protocollo storage a blocchi


.Prima di iniziare
Prima di creare un volume, esaminare i seguenti prerequisiti:

* È necessario disporre di un file system FSx per ONTAP nella console Workload Factory.
* Devi avere una macchina virtuale di storage.
* Per l'accesso al protocollo, completare quanto segue:
+
** Per configurare l'accesso al volume, è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.
** Devi configurare l'accesso per il protocollo selezionato, ovvero CIFS, NFS o iSCSI.






== Creare un volume

È possibile creare un volume utilizzando i seguenti strumenti disponibili in Codebox: API REST, CloudFormation e Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Scopri come utilizzare Codebox per l'automazione"^].


NOTE: Quando si utilizza Terraform da Codebox, il codice che si copia o si scarica nasconde `fsxadmin` e `vsadmin` password. Sarà necessario immettere nuovamente le password quando si esegue il codice.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, seleziona il menu a tre punti del file system in cui desideri creare un volume e seleziona *Crea volume*.
. Nella pagina Create volume (Crea volume), sotto General details (Dettagli generali), fornire i seguenti dettagli:
+
.. *Volume name*: Immettere un nome per il volume.
.. *Storage VM name* (Nome VM di archiviazione): Se si desidera, immettere un nome di VM di archiviazione.
.. *Stile volume*: Selezionare *FlexVol* o *FlexGroup* volume.
+
Per impostazione predefinita è selezionato lo stile del volume FlexVol.

+
La dimensione del volume di FlexGroup dipende dal numero di componenti e richiede 100 GiB per componente.

.. *Dimensione volume*: Immettere le dimensioni e l'unità del volume.
+
In alternativa, attivare l'espansione automatica del volume. Questa opzione è disponibile quando si seleziona *accesso al file* come tipo di accesso al volume.

.. *Aumento automatico del volume*: Facoltativamente, abilita l'aumento automatico del volume per espandere automaticamente la capacità del volume fino al raggiungimento della dimensione massima. Questa funzione si adatta all'aumento dell'utilizzo dei dati, garantendo operazioni senza interruzioni.
+
Specificare la dimensione massima di crescita del volume e l'unità di misura. Non è possibile impostare una dimensione di crescita massima inferiore alla dimensione del volume corrente

.. *Tags*: Opzionalmente, è possibile aggiungere fino a 50 tag.


. In accesso (solo per i file system con collegamenti associati), fornire i seguenti dettagli:
+
.. *Tipo di accesso*: Selezionare *accesso al file* o *Blocca accesso*. I campi aggiuntivi per configurare l'accesso al volume variano a seconda della selezione effettuata.
+
*** *Accesso ai file*: Consente a più utenti e dispositivi autorizzati di accedere al volume utilizzando i protocolli SMB/CIFS, NFS o dual (SMB/NFS).
+
Completare i seguenti campi per impostare l'accesso al volume ai file.

+
.... *Criterio di esportazione NFS*: Fornire i seguenti dettagli per fornire l'accesso NFS:
+
..... *Controllo di accesso*: Selezionare *criterio di esportazione personalizzato*, *criterio di esportazione esistente* o *Nessun accesso al volume* dal menu a discesa.
..... *Nome criterio di esportazione*:
+
Se è stato selezionato un criterio di esportazione personalizzato, selezionare un nome di criterio esistente dal menu a discesa.

+
Se è stato selezionato un criterio di esportazione esistente, immettere un nuovo nome per il criterio.

..... *Aggiungi regola criterio di esportazione*: In alternativa, per un criterio di esportazione personalizzato, è possibile aggiungere regole al criterio.


.... *CIFS share*: Fornire quanto segue:
+
..... *Nome*: Immettere il nome della condivisione CIFS per fornire l'accesso SMB.
..... *Autorizzazioni*: Selezionare controllo completo, lettura/scrittura, lettura o Nessun accesso, quindi immettere gli utenti o i gruppi separati da un punto e virgola ( ; ). Gli utenti o i gruppi rilevano la distinzione tra maiuscole e minuscole e il dominio dell'utente deve essere incluso nel formato "dominio\nome utente".


.... *Stile di protezione*: Per i volumi a doppio protocollo, selezionare lo stile di protezione UNIX o NTFS. UNIX è lo stile di protezione predefinito per i volumi a doppio protocollo. Per informazioni dettagliate sulla mappatura degli utenti in questo contesto, fare riferimento all'articolo del blog AWS link:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["Abilita carichi di lavoro multiprotocollo con Amazon FSX per NetApp ONTAP"^].


*** *Block access*: Consente agli host che eseguono applicazioni aziendali critiche di accedere al volume utilizzando il protocollo iSCSI. L'accesso a blocchi è disponibile solo quando le implementazioni scale-out del file system hanno sei coppie ha o meno.
+
Completare i seguenti campi per impostare il blocco dell'accesso al volume.

+
.... *Configurazione iSCSI*: Fornire i seguenti dettagli per configurare iSCSI per bloccare l'accesso al volume.
+
..... Selezionare *Crea un nuovo gruppo iniziatore* o *Mappa di un gruppo iniziatore esistente*.
..... Selezionare *sistema operativo host* dal menu a discesa.
..... Immettere un *nome gruppo iniziatore* per un nuovo gruppo iniziatore.
..... In host Initators (iniziatori host), aggiungere uno o più iniziatori host iSCSI Qualified Name (IQN).








. In termini di efficienza e protezione, fornire i seguenti dettagli:
+
.. *Efficienza di archiviazione*: Abilitata per impostazione predefinita. Seleziona per disabilitare la funzione.
+
ONTAP raggiunge l'efficienza di archiviazione utilizzando funzionalità di deduplicazione e compressione. La deduplica elimina i blocchi di dati duplicati. La compressione dei dati comprime i blocchi di dati per ridurre la quantità di storage fisico richiesta.

.. *Criterio snapshot*: Selezionare il criterio snapshot per specificare la frequenza e la conservazione degli snapshot.
+
Di seguito sono riportate le policy predefinite di AWS. Per i criteri di snapshot personalizzati, è necessario link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["associare un collegamento"] .

+
`default`:: Questo criterio crea automaticamente gli snapshot nella seguente pianificazione, con le copie snapshot più vecchie eliminate per fare spazio alle copie più recenti:
+
--
*** Un massimo di sei snapshot ogni ora prese cinque minuti dopo l'ora.
*** Massimo due istantanee giornaliere effettuate dal lunedì al sabato a 10 minuti dopo la mezzanotte.
*** Un massimo di due istantanee settimanali scattate ogni domenica a 15 minuti dopo la mezzanotte.
+

NOTE: Gli orari degli snapshot si basano sul fuso orario del file system, che per impostazione predefinita è UTC (Coordinated Universal Time). Per informazioni sulla modifica del fuso orario, consultare la link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["Visualizzazione e impostazione del fuso orario del sistema"^] documentazione di supporto di NetApp.



--
`default-1weekly`:: Questo criterio funziona allo stesso modo del `default` criterio, con la sola differenza che conserva solo uno snapshot della pianificazione settimanale.
`none`:: Questa policy non consente di acquisire istantanee. È possibile assegnare questo criterio ai volumi per impedire la creazione di snapshot automatiche.


.. *Criterio di tiering*: Selezionare il criterio di tiering per i dati memorizzati nel volume.
+
_Balanced (Auto)_ è la policy di tiering predefinita quando si crea un volume utilizzando la console workload Factory. Per ulteriori informazioni sulle policy di tiering dei volumi, fare riferimento a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacità di storage dei volumi"^] nella documentazione di AWS FSX per NetApp ONTAP. Nota: Workload Factory utilizza nomi basati su casi d'utilizzo nella console workload Factory per le policy di tiering e include i nomi delle policy di tiering di FSX per ONTAP tra parentesi.

.. *File immutabili*: Questa funzione, nota anche come SnapLock, è disattivata per impostazione predefinita. L'abilitazione dei file immutabili impedisce l'eliminazione o la sovrascrittura dei dati per un periodo di tempo stabilito. L'attivazione di questa funzione è possibile solo durante la creazione del volume. Una volta attivata, la funzione non può essere disattivata. Si tratta di una funzione premium di FSX per ONTAP con un costo aggiuntivo. Per ulteriori informazioni, consulta la link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["Come funziona SnapLock"^]documentazione di Amazon FSX per NetApp ONTAP.
+
L'attivazione della funzione file immutabili assegna in modo permanente i file in questo volume a uno stato WORM (write-once-Read-many) immutabile.

+
Modalità di conservazione:: È possibile scegliere tra due modalità di conservazione: _Enterprise_ o _Compliance_.
+
--
*** In modalità _Enterprise_, un file immutabile, o SnapLock, può essere eliminato dall'amministratore durante il periodo di conservazione.
*** In modalità _Compliance_, un file WORM non può essere eliminato prima della scadenza del periodo di conservazione. Analogamente, il volume immutabile non può essere eliminato fino alla scadenza dei periodi di conservazione di tutti i file all'interno del volume.


--
Periodo di conservazione:: Il periodo di conservazione ha due impostazioni: _Retention policy_ e _retention period_. Il _Retention policy_ definisce per quanto tempo conservare i file in uno stato WORM immutabile. È possibile specificare un criterio di conservazione personalizzato o utilizzare il criterio di conservazione predefinito (non specificato), ossia 30 anni. I periodi di conservazione minimo e massimo definiscono l'intervallo di tempo consentito per il blocco dei file.
+
--
NOTA:: Anche dopo la scadenza del periodo di conservazione, non è possibile modificare un file WORM. È possibile solo eliminarlo o impostare un nuovo periodo di conservazione per riattivare la protezione WORM.


--
Commit automatico:: È possibile attivare la funzione di autocommit. La funzionalità di autocommit assegna un file allo stato WORM su un volume SnapLock se il file non viene modificato per la durata del periodo di autocommit. La funzione di invio automatico è disattivata per impostazione predefinita. È necessario assicurarsi che i file di cui si desidera eseguire l'autocommit risiedano in un volume SnapLock.
Modalità di aggiunta volume:: Non è possibile modificare i dati esistenti in un file protetto da WORM. Tuttavia, i file immutabili consentono di mantenere la protezione per i dati esistenti utilizzando file che possono essere allegati WORM. Ad esempio, è possibile generare file di registro o conservare i dati in streaming audio o video durante la scrittura incrementale dei dati. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["Ulteriori informazioni sulla modalità di aggiunta di un volume"^] Nella documentazione di Amazon FSX per NetApp ONTAP.
+
--
.Procedura per i file immutabili
... Selezionare per attivare *file immutabili basati su SnapLock*.
... Selezionare la casella per accettare e procedere.
... Selezionare *Abilita*.
... *Modalità di conservazione*: Selezionare la modalità *Enterprise* o *Compliance*.
... *Periodo di conservazione*:
+
**** Selezionare il criterio di conservazione:
+
***** *Non specificato*: Imposta il criterio di conservazione su 30 anni.
***** *Specifica periodo*: Immettere il numero di secondi, minuti, ore, giorni, mesi o anni per impostare un criterio di conservazione personalizzato.


**** Selezionare i periodi di conservazione minimo e massimo:
+
***** *Minimo*: Immettere il numero di secondi, minuti, ore, giorni, mesi o anni per impostare il periodo di conservazione minimo.
***** *Massimo*: Immettere il numero di secondi, minuti, ore, giorni, mesi o anni per impostare il periodo di conservazione massimo.




... *Autocommit*: Consente di disabilitare o abilitare l'autocommit. Se si attiva l'autocommit, impostare il periodo di autocommit.
... *Modalità di aggiunta volume*: Consente di disattivare o attivare. Consente di aggiungere nuovi contenuti ai file WORM.


--


.. *ARP/AI*: NetApp Autonomous Ransomware Protection with AI (ARP/AI) è abilitato per impostazione predefinita quando un collegamento è associato al file system. link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Scopri di più su ARP/AI"]. Accettare la dichiarazione per procedere.
+
Se la funzionalità non è disponibile, il motivo è uno dei seguenti:

+
*** Nessun collegamento è associato al file system. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.
*** I volumi con file immutabili e i volumi con protocolli iSCSI e NVMe non sono supportati per ARP/AI.
*** Il file system ha già una policy ARP/AI.




. In Configurazione avanzata, fornire quanto segue:
+
.. *Percorso di giunzione*: Inserire la posizione nello spazio dei nomi della VM di archiviazione in cui viene montato il volume. Il percorso di giunzione predefinito è `/<volume-name>`.
.. *Lista aggregati*: Solo per volumi FlexGroup. Aggiunta o rimozione degli aggregati. Il numero minimo di aggregati è uno.
.. *Numero di componenti*: Solo per volumi FlexGroup. Immettere il numero di componenti per aggregato. 100 GiB è richiesto per ciascun componente.


. Selezionare *Crea*.


.Risultato
La fabbrica del carico di lavoro avvia la creazione del volume. Una volta creato, il sistema visualizza il nuovo volume nella scheda Volumi.
