---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: Creare uno snapshot manuale di un volume FSx for ONTAP in NetApp Workload Factory.  Gli snapshot sono versioni puntuali del contenuto del volume. 
---
= Crea una snapshot manuale di un volume FSX per ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Creare uno snapshot manuale di un volume FSx for ONTAP in NetApp Workload Factory.  Gli snapshot sono versioni puntuali del contenuto del volume.

Gli snapshot sono risorse di volumi e offrono acquisizioni istantanee dei dati che occupano spazio solo per i dati modificati. A causa del cambiamento dei dati nel tempo, le snapshot solitamente occupano più spazio man mano che diventano più datate.

FSX per ONTAP Volumes usa il copy-on-write just-in-time in modo che i file non modificati nelle snapshot non consumino la capacità del volume.


NOTE: Le snapshot non sono copie dei tuoi dati. Se vuoi creare copie dei tuoi dati, prendi in considerazione l'utilizzo di FSX per ONTAP o delle funzionalità di replica dei volumi.

.Prima di iniziare
Per creare uno snapshot manuale di un volume è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu azioni del file system che contiene il volume per cui creare uno snapshot, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda *Volumi*, seleziona il menu delle azioni per il volume da proteggere con gli snapshot.
. Selezionare *Azioni di protezione dei dati* e quindi *Gestisci snapshot*.
. Dalla pagina Gestisci snapshot, seleziona *Crea snapshot*.
. Nella finestra di dialogo Crea uno snapshot, procedi come segue:
+
.. Immettere un nome per lo snapshot nel campo *Nome snapshot*.
.. Facoltativamente, seleziona un'etichetta o creane una nuova.
.. Impostare *periodo di conservazione* come numero di ore, giorni, mesi o anni.
.. Facoltativo: *Rendi questo snapshot immutabile* per evitare che venga eliminato durante il periodo di conservazione.
+
Accettare la dichiarazione relativa agli snapshot immutabili.



. Selezionare *Crea*.

