---
sidebar: sidebar 
permalink: delete-svm.html 
keywords: delete storage vm, delete svm, remove svm 
summary: 'Elimina una Storage VM (SVM) che non ti serve più in una configurazione di file system FSX per ONTAP.' 
---
= Elimina una VM di archiviazione in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Elimina una Storage VM (SVM) che non ti serve più in una configurazione di file system FSX per ONTAP.

.Prima di iniziare
Prima di eliminare una macchina virtuale di storage, rivedere quanto segue:

* Verifica che nessuna applicazione stia accedendo ai dati nella SVM.
* Elimina tutti i volumi non root collegati alla SVM.


.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Nella scheda VM di archiviazione, selezionare il menu delle azioni della VM di archiviazione per cui configurare Active Directory.
. Selezionare *Elimina VM di archiviazione*.
. Nella finestra di dialogo Delete storage VM, digitare "delete" per eliminare la VM di storage.
. Selezionare *Elimina* per confermare.

