---
sidebar: sidebar 
permalink: delete-svm.html 
keywords: delete storage vm, delete svm, remove svm 
summary: 'Elimina una Storage VM (SVM) che non ti serve più in una configurazione di file system FSX per ONTAP.' 
---
= Eliminazione di una macchina virtuale per lo storage nella fabbrica di workload BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Elimina una Storage VM (SVM) che non ti serve più in una configurazione di file system FSX per ONTAP.

.Prima di iniziare
Prima di eliminare una macchina virtuale di storage, rivedere quanto segue:

* Verifica che nessuna applicazione stia accedendo ai dati nella SVM.
* Elimina tutti i volumi non root collegati alla SVM.


.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, seleziona il menu a tre punti del file system da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Nella scheda Storage VM, seleziona il menu a tre punti della VM storage per cui configurare Active Directory.
. Selezionare *Elimina VM di archiviazione*.
. Nella finestra di dialogo Delete storage VM, digitare "delete" per eliminare la VM di storage.
. Selezionare *Delete* (Elimina).

