---
sidebar: sidebar 
permalink: delete-volume.html 
keywords: delete volume, volume deletion 
summary: Elimina un volume nel file system FSX per ONTAP che non è più necessario e per liberare spazio. Questa operazione è irreversibile. 
---
= Elimina un volume in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Elimina un volume nel file system FSX per ONTAP che non è più necessario e per liberare spazio. Questa operazione è irreversibile.

.Prima di iniziare
Prima di eliminare un volume, prendere in considerazione quanto segue:

* Relazioni di replica: È necessario link:delete-replication.html["eliminare tutte le relazioni di replica esistenti"] per questo volume prima di eliminare il volume in modo che non rimangano relazioni interrotte.
* Snapshot locali: Tutti gli snapshot associati a questo file system FSX per ONTAP verranno eliminati in modo permanente.
* Backup FSX per ONTAP: Le copie di backup di FSX per ONTAP rimarranno e potrai comunque utilizzarli.
* File e snapshot immutabili: I volumi che contengono file immutabili e snapshot non possono essere eliminati fino al termine del periodo di conservazione.


.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare l'azione del file system con il volume da eliminare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda Volumi, selezionare il menu azioni del volume da eliminare.
. Selezionare *azioni di base*, quindi *Elimina volume*.
. Nella finestra di dialogo Elimina volume, effettuare le seguenti operazioni:
+
.. In alternativa, selezionare *Backup del volume* per eseguire il backup del volume prima dell'eliminazione.
+
Il backup rimane nel file system finché non viene eliminato manualmente.

.. Selezionare *continua*.
.. Digitare "delete" per eliminare il volume.
.. Selezionare *Elimina* per confermare.



