---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: 'Abilita l"aumento automatico del volume per consentire a Workload Factory di gestire la capacità del volume per te. È possibile disattivarla in qualsiasi momento.' 
---
= Abilita l'aumento automatico del volume nella fabbrica dei carichi di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Abilita l'aumento automatico del volume per consentire a Workload Factory di gestire la capacità del volume per te. È possibile disattivarla in qualsiasi momento.

In alternativa, è possibile aumentare manualmente la capacità del volume di un volume in qualsiasi momento utilizzando link:increase-volume-capacity.html["funzione di aumento della capacità del volume"].


NOTE: L'espansione automatica dei volumi non è supportata per i volumi iSCSI.

.Prima di iniziare
Per attivare la crescita automatica del volume, è necessario link:manage-links.html["associare un collegamento"]. Se non si dispone di un collegamento esistente, link:create-link.html["creare un collegamento"]. Per associare un collegamento nel file system, selezionare *Associa collegamento* in *Nome account*. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda FSX per ONTAP, selezionare il menu a tre punti del file system con il volume da aggiornare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda volumi, selezionare il menu a tre punti per il volume che si desidera modificare.
. Selezionare *Azioni di base*, quindi *Imposta aumento automatico volume*.
. Nella finestra di dialogo Imposta aumento automatico, abilita l'aumento automatico del volume per espandere automaticamente la capacità del volume fino al raggiungimento della dimensione massima. Questa funzione si adatta all'aumento dell'utilizzo dei dati, garantendo operazioni senza interruzioni.
+
Specificare la dimensione massima di crescita del volume e l'unità di misura. La dimensione massima di crescita non può essere inferiore alla dimensione del volume corrente.

. Selezionare *Applica*.

