---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, file system capacity 
summary: Abilitando questa funzionalità, i workload Factory aggiungono automaticamente storage incrementale a un file system FSX per ONTAP con il variare delle esigenze di capacità nel tempo. 
---
= Abilita la gestione automatica della capacità per un file system FSX per ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Abilitando questa funzionalità, i workload BlueXP  possono aggiungere automaticamente storage incrementale a un file system FSX per ONTAP con il variare delle esigenze di capacità nel tempo.

.A proposito di questa attività
Ogni 30 minuti viene eseguita una scansione del file system FSX per ONTAP per determinare se è necessario aggiungere lo storage incrementale e controllare gli inode di volumi disponibili o il numero massimo di file e cartelle in un volume, in modo che il loro conteggio aumenti in base alle soglie di gestione automatica della capacità configurate.

Questa funzione può essere gestita da un solo account.

La quantità massima di capacità di storage SSD per tutti i file system FSX per ONTAP è di 524.288 GiB. Per richiedere un aumento delle quote, fai riferimento alla link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Quote"^] documentazione di AWS FSX per NetApp ONTAP.

.Prima di iniziare
Per completare questa attività, è necessario disporre di credenziali con autorizzazioni _automatizza_ in fabbrica del carico di lavoro.

Per assicurarsi che gli inode del volume aumentino insieme alla capacità di memorizzazione, è necessario link:manage-links.html["associare un collegamento"]. Se non si dispone di un collegamento esistente, link:create-link.html["creare un collegamento"]. Per associare un collegamento nel file system, selezionare *Associa collegamento* in *Nome account*. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system per abilitare la gestione automatica della capacità.
. Selezionare *Gestisci*.
. In informazioni, selezionare l'icona a forma di matita accanto a *Gestione automatica della capacità*. L'icona a forma di matita viene visualizzata accanto alla freccia del menu a discesa quando il mouse passa sopra la riga *Gestione automatica della capacità*.
. Nella finestra di dialogo *Gestione automatica della capacità*, specificare quanto segue:
+
.. *Credenziali*: Selezionare le credenziali con autorizzazioni _automatizza_ dal menu a discesa.
.. Selezionare il pulsante di abilitazione per *abilitare la gestione automatica della capacità*.
+
In alternativa, disattivare la funzione. Se è necessario aumentare la capacità del file system, è necessario prima disabilitare la gestione automatica della capacità.

.. *Soglia capacità*: Immettere la dimensione massima per il file system FSX per ONTAP.
.. *Incrementi di aumento della capacità*: Immettere la percentuale per aumentare la capacità in modo incrementale.


. Selezionare *Applica*.


.Risultato
Ogni 30 minuti viene eseguita una scansione del file system per determinare se il file system necessita di capacità aggiuntiva.
