---
sidebar: sidebar 
permalink: explore-savings.html 
keywords: cost, savings, compare costs, EBS, EFS, FSx for Windows file servers FSx for ONTAP 
summary: 'Esplora i risparmi per i carichi di lavoro di storage nello storage di Amazon Elastic Block Store (EBS), Elastic file System (EFS) ed FSX per Windows file Server su AWS FSX per NetApp ONTAP.' 
---
= Scopri i risparmi in FSX per ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Esplora i risparmi per i workload di storage che utilizzano Amazon Elastic Block Store (EBS), Elastic file System (EFS) ed FSX per Windows file Server rispetto ad FSX per NetApp ONTAP.

Workload Factory dispone di un calcolatore integrato di risparmi dello storage che ti permette di confrontare i tuoi ambienti di storage Amazon con FSX per ONTAP. Puoi esplorare i risparmi con o senza fornire le tue credenziali AWS e personalizzare le impostazioni di configurazione del tuo ambiente storage. Quando fornisci le credenziali AWS, puoi selezionare una o più istanze di Amazon Elastic Block Store, ad esempio, e lasciare che workload Factory faccia il confronto automaticamente. Il calcolatore determina, manualmente o automaticamente, quale servizio di storage offre il costo più basso per le vostre esigenze di storage.

Se il calcolatore di storage determina che lo storage più conveniente è FSX per ONTAP, puoi creare o salvare le configurazioni di FSX per ONTAP e utilizzare Codebox per generare modelli di Infrastructure-as-Code indipendentemente dalle autorizzazioni concesse a workload Factory.



== Opzioni della calcolatrice

Sono disponibili due opzioni di calcolatore per effettuare il confronto tra i costi dei tuoi sistemi e FSX per ONTAP -- personalizzazione e rilevamento automatico per i tuoi ambienti di storage Amazon.

Esplorazione dei risparmi tramite personalizzazione: Sono state fornite le impostazioni di configurazione per un ambiente di storage che includono caso di utilizzo, regione, numero di volumi o file system, quantità di storage, frequenza di Snapshot, quantità modificata per snapshot, IOPS sottoposti a provisioning, throughput e altro ancora.

Scopri i risparmi per gli ambienti di storage rilevati: Workload Factory si collega agli ambienti di storage AWS esistenti e sfrutta i dettagli del calcolatore per il confronto automatico. Per utilizzare la modalità automatica, è necessario concedere autorizzazioni automatiche. È possibile modificare il caso di utilizzo, ma tutti gli altri dettagli vengono determinati automaticamente nel calcolo.



== Esplora i risparmi tramite la personalizzazione

Seguire i passaggi nella scheda per la selezione della memoria.

[role="tabbed-block"]
====
.Amazon Elastic Block Store (EBS)
--
.Fasi
. Accedere a. link:https://console.workloads.netapp.com/["Console di workload Factory"^]
. In Storage, seleziona *Explore Savings*, quindi *Amazon Elastic Block Store (EBS)*.
. Nel calcolatore del risparmio dello storage, fornisci i seguenti dettagli:
+
.. *Caso di utilizzo*: Obbligatorio. Selezionare un caso d'uso dal menu a discesa. Il caso d'utilizzo selezionato determina le caratteristiche del file system FSX per ONTAP da confrontare.
.. *Regione*: Facoltativo. Selezionare la regione per la configurazione EBS dal menu a discesa.
.. *Selezionare il tipo di volume EBS*: Opzionale. Selezionare il tipo di volume EBS utilizzato per la configurazione.
.. *Numero di volumi*: Facoltativo. Immettere il numero di volumi nella configurazione EBS.
.. *Quantità di storage per volume (TiB)*: Opzionale. Immettere la quantità di storage per volume in TiB.
.. *Frequenza istantanea*: Opzionale. Selezionare la frequenza delle istantanee per la configurazione EBS.
.. *Importo modificato per istantanea (GiB)*: Facoltativo. Solo per lo storage Snapshot. Immettere la quantità modificata per istantanea in GiB.
.. *IOPS con provisioning per volume*: Opzionale. Per volumi GP3, io1 e IO2. Inserisci gli IOPS forniti per volume.
.. *Throughput (MIB/s)*: Opzionale. Solo per volumi GP3. Immettere la capacità di trasmissione in MIB/s per volume.




--
.Amazon FSX per Windows file Server
--
.Fasi
. Accedere a. link:https://console.workloads.netapp.com/["Console di workload Factory"^]
. In archiviazione, selezionare *Esplora risparmi*, quindi *Amazon FSX per Windows file Server*.
. Nel calcolatore del risparmio dello storage, fornisci i seguenti dettagli:
+
.. *Caso di utilizzo*: Obbligatorio. Selezionare un caso d'uso dal menu a discesa. Il caso d'utilizzo selezionato determina le caratteristiche del file system FSX per ONTAP da confrontare.
.. *Regione*: Facoltativo. Selezionare l'area per la configurazione di FSX per Windows file Server dal menu a discesa.
.. *Tipo di distribuzione*: Opzionale. Selezionare *zona di disponibilità singola* o *più zone di disponibilità*.
.. *Tipo di archiviazione*: Il tipo di archiviazione SSD è selezionato per impostazione predefinita.
.. *Capacità di archiviazione (TiB)*: Opzionale. Immettere la capacità di memorizzazione per la configurazione.
.. *Risparmio della deduplica (%)*: Facoltativo. Immettere la percentuale di risparmio della capacità prevista dalla deduplica.
.. *Frequenza istantanea*: Opzionale. Selezionare la frequenza delle istantanee per la configurazione.
.. *Importo modificato per istantanea (GiB)*: Facoltativo. Solo per lo storage Snapshot. Immettere la quantità modificata per istantanea in GiB.
.. *IOPS SSD con provisioning*: Opzionale. Inserisci gli IOPS SSD di cui è stato eseguito il provisioning.
.. *Throughput (MIB/s)*: Opzionale. Immettere il throughput in MIB/s.




--
.Amazon Elastic file System (EFS)
--
.Fasi
. Accedere a. link:https://console.workloads.netapp.com/["Console di workload Factory"^]
. Nell'archiviazione, selezionare *Esplora risparmi*, quindi *Amazon Elastic file System (EFS)*.
. Nel calcolatore del risparmio dello storage, fornisci i seguenti dettagli:
+
.. *Caso di utilizzo*: Obbligatorio. Selezionare un caso d'uso dal menu a discesa. Il caso d'utilizzo selezionato determina le caratteristiche del file system FSX per ONTAP da confrontare.
.. *Regione*: Facoltativo. Selezionare l'area per la configurazione di FSX per Windows file Server dal menu a discesa.
.. *Tipo file system*: Opzionale. Selezionare *Regionale* o *una zona*.
.. *Capacità di archiviazione (TiB)*: Opzionale. Immettere la capacità di archiviazione della configurazione EFS.
.. *Dati utilizzati di frequente (%)*: Facoltativo. Immettere la percentuale di dati a cui si accede di frequente.
.. *Modalità throughput*: Opzionale. Selezionare *throughput fornito* o *throughput elastico*.
.. *Throughput (MIB/s)*: Opzionale. Immettere il throughput in MIB/s.




--
====
Dopo aver fornito i dettagli per la configurazione del sistema di archiviazione, esaminare i calcoli e i consigli forniti nella pagina.

Inoltre, scorri verso il basso fino in fondo alla pagina fino a *Esporta PDF* o *Visualizza i calcoli*.

Per passare a FSX per ONTAP, seguire le istruzioni riportate in <<Implementa FSX per i file system ONTAP,Implementa FSX per i file system ONTAP>>.



== Esplora i risparmi per gli ambienti di storage rilevati

.Prima di iniziare
Per workload Factory, per rilevare gli ambienti di storage Amazon Elastic Block Store (EBS), Elastic file System (EFS) ed FSX per Windows file Server nel tuo account AWS, assicurati di utilizzare il tuo link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["concedi autorizzazioni _automatizza_"^] account AWS.


NOTE: Questa opzione di calcolo non supporta i calcoli per gli snapshot EBS e le copie shadow di FSX per Windows file Server. Quando si esplorano i risparmi tramite la personalizzazione, è possibile fornire dettagli sugli snapshot EBS ed FSX per Windows file Server.

Seguire i passaggi nella scheda per la selezione della memoria.

[role="tabbed-block"]
====
.Amazon Elastic Block Store (EBS)
--
.Fasi
. Accedere a. link:https://console.workloads.netapp.com/["Console di workload Factory"^]
. Da archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nell'inventario di archiviazione, selezionare la scheda *Esplora risparmio*.
. Nella scheda *Elastic Block Store (EBS)*, selezionare le istanze da confrontare con FSX per ONTAP e fare clic su *Esplora risparmio*.
. Viene visualizzato il calcolatore del risparmio dello storage. Le seguenti caratteristiche del sistema storage sono precompilate in base alle istanze selezionate:
+
.. *Caso d'utilizzo*: Il caso d'utilizzo per la configurazione. Se necessario, è possibile modificare il caso di utilizzo.
.. *Volumi selezionati*: Il numero di volumi nella configurazione EBS
.. *Quantità di storage totale (TiB)*: La quantità di storage per volume in TiB
.. *IOPS totali con provisioning*: Per volumi GP3, io1 e IO2
.. *Throughput totale (MIB/s)*: Solo per volumi GP3




--
.Amazon FSX per Windows file Server
--
.Fasi
. Accedere a. link:https://console.workloads.netapp.com/["Console di workload Factory"^]
. Da archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nell'inventario di archiviazione, selezionare la scheda *Esplora risparmio*.
. Selezionare la scheda *FSX per Windows file Server*.
. Seleziona le istanze da confrontare con FSX per ONTAP e fai clic su *Esplora risparmi*.
. Viene visualizzato il calcolatore del risparmio dello storage. Le seguenti caratteristiche del sistema storage sono precompilate in base al tipo di implementazione delle istanze selezionate:
+
.. *Caso d'utilizzo*: Il caso d'utilizzo per la configurazione. Se necessario, è possibile modificare il caso di utilizzo.
.. *File system selezionati
.. *Quantità totale di storage (TiB)*
.. *IOPS SSD con provisioning*
.. *Throughput (MIB/s)*




--
.Amazon Elastic file System (EFS)
--
.Fasi
. Accedere a. link:https://console.workloads.netapp.com/["Console di workload Factory"^]
. Da archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nell'inventario di archiviazione, selezionare la scheda *Esplora risparmio*.
. Selezionare la scheda * Elastic file System (EFS)*.
. Seleziona le istanze da confrontare con FSX per ONTAP e fai clic su *Esplora risparmi*.
. Viene visualizzato il calcolatore del risparmio dello storage. Le seguenti caratteristiche del sistema storage sono precompilate in base alle istanze selezionate:
+
.. *Caso d'utilizzo*: Il caso d'utilizzo per la configurazione. Se necessario, è possibile modificare il caso di utilizzo.
.. *Totale file system*
.. *Quantità totale di storage (TiB)*
.. *Throughput totale fornito (MIB/s)*
.. *Throughput elastico totale - lettura (GiB)*
.. *Throughput elastico totale – scrittura (GiB)*




--
====
Dopo aver fornito i dettagli per la configurazione del sistema di archiviazione, esaminare i calcoli e i consigli forniti nella pagina.

Inoltre, scorri verso il basso fino in fondo alla pagina fino a *Esporta PDF* o *Visualizza i calcoli*.



== Implementa FSX per i file system ONTAP

Se desideri passare a FSX for ONTAP per risparmiare sui costi, fai clic su *Crea* per creare il file system direttamente dalla procedura guidata Crea un file system FSX per ONTAP oppure fai clic su *Salva* per salvare le configurazioni consigliate in un secondo momento.

Metodi di distribuzione:: In modalità _automatizza_, puoi implementare il file system FSX per ONTAP direttamente da workload Factory. È inoltre possibile copiare il contenuto dalla finestra Codebox e distribuire il sistema utilizzando uno dei metodi Codebox.
+
--
In modalità _BASIC_, è possibile copiare il contenuto dalla finestra Codebox e distribuire il file system FSX per ONTAP utilizzando uno dei metodi Codebox.

--

