---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: 'La farm di workload BlueXP  per i database analizza le configurazioni di Microsoft SQL Server offrendo approfondimenti e consigli per aiutarti a raggiungere l"eccellenza operativa.' 
---
= Implementa configurazioni del file system con un'architettura ottimale
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Utilizzando informazioni e suggerimenti sull'analisi della configurazione, sfrutta Workload Factory per implementare le best practice per i tuoi file system FSx for ONTAP . Puoi facilmente verificare lo stato di corretta architettura, individuare eventuali problemi nelle tue configurazioni e intervenire per migliorare l'architettura di qualsiasi sistema non ottimizzato in termini di affidabilità, sicurezza, efficienza, prestazioni e costi.

link:configuration-analysis.html["Scopri di più sull'analisi della configurazione e sullo stato ben progettato nella fabbrica dei carichi di lavoro."]

.A proposito di questa attività
Workload Factory analizza quotidianamente le configurazioni di distribuzione del file system Amazon FSx for NetApp ONTAP . L'analisi giornaliera fornisce informazioni sullo stato di corretta architettura, oltre a informazioni e suggerimenti, con opzioni per risolvere automaticamente i problemi di configurazione, in modo che il file system soddisfi le best practice.

Puoi esaminare i suggerimenti per i problemi di configurazione dei tuoi file system e risolvere i problemi dall'inventario di archiviazione all'interno della console di Workload Factory.

Cosa viene analizzato:: Workload Factory analizza lo stato con un'architettura appropriata delle seguenti configurazioni per i file system FSX per ONTAP:
+
--
* Soglia di capacità SSD
* Tiering dei dati
* Istantanee locali pianificate
* FSx per backup ONTAP
* Replica remota dei dati
* Efficienza dello storage
* Gestione automatica della capacità


--


.Prima di iniziare
* È necessario disporre di credenziali con autorizzazioni di _sola lettura_ o _lettura/scrittura_. link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Scopri come concedere autorizzazioni al tuo account AWS"^].
* Assicurarsi di rivedere attentamente ogni suggerimento prima di selezionare per correggere un'impostazione o una configurazione.



NOTE: Il processo di correzione potrebbe causare tempi di inattività delle istanze o interruzioni del servizio. Prima di risolvere un problema di configurazione, leggere attentamente il suggerimento.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, accedere alla colonna *Stato ben strutturato* e selezionare i problemi che il file system deve risolvere.
. Nel dashboard ben strutturato per il file system, filtra i problemi di configurazione per categorie, sottocategorie, stato, gravità e tag.
. Selezionare la freccia dell'elenco a discesa per visualizzare il suggerimento per qualsiasi configurazione. Verificare attentamente il suggerimento.
+
Il suggerimento spiega le Best practice e i potenziali errori di configurazioni non ottimizzate.

. Selezionare *Correggi*.
+
Quando *Visualizza e correggi* è un'opzione, selezionare i volumi interessati da correggere.

. Rivedere il riepilogo e le azioni visualizzate nella finestra di dialogo per scoprire cosa accadrà se si sceglie di risolvere il problema. Alcune operazioni possono causare tempi di inattività delle istanze o interruzioni del servizio.
. Selezionare *continua* per risolvere il problema di configurazione.


.Risultato
Viene avviato il processo di risoluzione del problema. Selezionare il menu delle impostazioni dell'account e quindi selezionare *Tracker* per visualizzare lo stato dell'operazione.
