---
sidebar: sidebar 
permalink: increase-file-system-capacity.html 
keywords: increase capacity, increase file system capacity, increase FSx capacity 
summary: 'Aumentare manualmente la capacità di storage SSD di un file system FSX per ONTAP quando la quantità di capacità di storage SSD utilizzata supera una soglia specificata dall"utente.' 
---
= Aumenta la capacità del file system in una fabbrica con carichi di lavoro BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aumentare manualmente la capacità di storage SSD di un file system FSX per ONTAP quando la quantità di capacità di storage SSD utilizzata supera una soglia specificata dall'utente.

In alternativa, puoi link:enable-auto-capacity-management.html["attivare la funzione di gestione automatica della capacità"] fare in modo che la fabbrica dei carichi di lavoro gestisca la capacità del file system al tuo posto.

.A proposito di questa attività
L'aumento della capacità dei file system influisce sugli IOPS per il file system FSX for ONTAP.

Se si sceglie automaticamente link:provision-iops.html["Provisioning degli IOPS"] per un file system, gli IOPS aumentano di 3 volte ogni aumento di 1 GiB nella capacità degli SSD.

link:provision-iops.html["Provisioning degli IOPS"]Manualmente, potrebbe essere necessario aumentare l'allocazione degli IOPS per supportare l'aumentata capacità del file system.

Per i limiti della capacità di storage degli SSD, fai riferimento alla link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Quote"^] documentazione di AWS FSX per NetApp ONTAP.

.Prima di iniziare
Per aumentare la capacità di un file system, è necessario innanzitutto link:enable-auto-capacity-management.html["disattivare la gestione automatica della capacità"].

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system per aumentare la capacità di.
. Selezionare *Gestisci*.
. In informazioni, selezionare l'icona a forma di matita accanto a *distribuzione della capacità*. L'icona a forma di matita viene visualizzata accanto alla freccia del menu a discesa quando il mouse passa sopra la riga *distribuzione della capacità*.
. Nella finestra di dialogo dimensioni memoria SSD, immettere un numero per *capacità fornita*.
. Seleziona l'unità per la capacità sottoposta a provisioning.
. Selezionare *Applica*.

