---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: È possibile aumentare manualmente la capacità di un volume in NetApp Workload Factory in qualsiasi momento. 
---
= Aumenta la capacità del volume in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aumenta manualmente la capacità di un volume in qualsiasi momento in NetApp Workload Factory.

Facoltativamente, puoilink:edit-volume-autogrow.html["attivare la funzione di crescita automatica"] per consentire a Workload Factory di gestire la capacità del volume per te.

.A proposito di questa attività
Per una LUN iSCSI, questa operazione aumenta la dimensione del LUN host. Una volta aumentata la capacità, seguire la procedura fornita dal sistema operativo host per rilevare le nuove dimensioni del LUN ed espandere il file system del LUN.

.Prima di iniziare
Per aumentare la capacità del volume, è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system con il volume da aggiornare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda Volumi, selezionare il menu delle azioni del volume per cui si desidera aumentare la capacità.
. Selezionare *azioni di base*, quindi *aumenta capacità volume*.
. Nella finestra di dialogo di aumento della capacità del volume, fornire quanto segue:
+
.. Selezionare un formato più grande.
.. Se necessario, sostituire l'unità.


. Selezionare *Aumenta* per applicare la modifica.

