---
sidebar: sidebar 
permalink: increase-file-system-capacity.html 
keywords: adjust capacity, elastic file system capacity, increase file system capacity, increase FSx capacity, decrease file system capacity, decrease FSx capacity 
summary: Regola manualmente la capacità di archiviazione SSD di un file system FSx for ONTAP per soddisfare le esigenze dei carichi di lavoro basati sui progetti con diversi set di lavoro attivi. 
---
= Regola la capacità del file system in Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Regola manualmente la capacità di archiviazione dell'unità a stato solido (SSD) di un file system FSx for ONTAP per soddisfare le esigenze dei carichi di lavoro basati sui progetti con diversi set di lavoro attivi.

Aumentare la capacità di archiviazione SSD di un file system FSx for ONTAP quando la quantità di capacità di archiviazione SSD utilizzata supera una soglia specificata oppure ridurre la capacità di archiviazione SSD quando i set di lavoro sono inattivi per migliorare l'efficienza dei costi.

In alternativa, puoilink:enable-auto-capacity-management.html["attivare la funzione di gestione automatica della capacità"] quindi Workload Factory gestisce la capacità del file system per te.


NOTE: La riduzione della capacità di archiviazione SSD è supportata solo per i file system di seconda generazione.

.A proposito di questa attività
Grazie alla capacità elastica del file system, puoi adattare dinamicamente la capacità dei tuoi file system alle esigenze dei tuoi carichi di lavoro.

La regolazione della capacità del file system influisce sugli IOPS del file system FSx per ONTAP .

Quando automaticamentelink:provision-iops.html["Provisioning degli IOPS"] per un file system, gli IOPS aumentano o diminuiscono di 3 IOPS per ogni aumento o diminuzione di 1 GiB nella capacità SSD.

link:provision-iops.html["Provisioning degli IOPS"]Manualmente, potrebbe essere necessario aumentare l'allocazione degli IOPS per supportare l'aumentata capacità del file system.

Per i limiti della capacità di storage degli SSD, fai riferimento alla link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Quote"^] documentazione di AWS FSX per NetApp ONTAP.

.Prima di iniziare
Per regolare la capacità di un file system, è necessario primalink:enable-auto-capacity-management.html["disattivare la gestione automatica della capacità"] .

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dalla Dashboard, seleziona *Regola capacità SSD*.
. Selezionare il file system per il quale si desidera regolare la capacità, quindi selezionare *Continua*.
+
*Potenziali risparmi* è la raccomandazione per la riduzione della capacità.

. Nella finestra di dialogo Regola capacità SSD, immettere un numero per *Capacità fornita*.
. Seleziona l'unità per la capacità sottoposta a provisioning.
. Selezionare *Applica*.

