---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. 
---
= Limitazioni note di Amazon FSX per NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni.



== Supporto regionale

Le seguenti regioni AWS non sono supportate:

* regioni della Cina
* Regioni GovCloud (USA)
* Nuvola segreta
* Nuvola top secret




== Aggiunta delle limitazioni di coppie ha

* Questa operazione potrebbe richiedere circa 30 minuti.
* L'aggiunta di coppie ha limita le seguenti operazioni: Aggiunta di altre coppie ha, provisioning di IOPS, aumento della capacità SSD e aggiornamento della capacità di throughput.




== Supporto regione di capacità di throughput



=== Implementazioni scale-up

Le configurazioni scale-up sono supportate fino a 2 GB/s in tutte le regioni. Le seguenti regioni supportano fino a 4 GB/s di capacità di throughput massima per le implementazioni scale-up: Regione US East (Ohio), regione US East (N. Virginia), regione US West (Oregon) ed Europa (Irlanda).



=== Implementazioni con scalabilità orizzontale

Le seguenti regioni supportano una capacità di throughput massima fino a 6 GB/s per distribuzioni scalabili: Stati Uniti orientali (Virginia settentrionale e Ohio), Stati Uniti occidentali (California settentrionale e Oregon), Europa (Francoforte, Irlanda e Stoccolma) e Asia Pacifico (Singapore e Sydney).



== Gestione della capacità

* La funzione di crescita automatica dei volumi non è attualmente supportata per il protocollo iSCSI.
* Quando la funzione di gestione automatica della capacità è in esecuzione, non è consentito l'aumento manuale della capacità.
* La disattivazione della funzione di gestione automatica della capacità è possibile solo con le stesse autorizzazioni utilizzate per attivarla.
* Quando la gestione automatica della capacità è abilitata, è necessario un collegamento per garantire che gli inode del volume aumentino insieme alla capacità di archiviazione.




== VM di storage

Il numero di VM di archiviazione è limitato per SKU.  La creazione di VM di archiviazione oltre la limitazione non è supportata in Workload Factory.^1^

Fare riferimento a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Gestione di FSX per ONTAP Storage Virtual Machine"^] nella documentazione AWS per il numero massimo di SVM per file system.



== Supporto del protocollo iSCSI

* Il protocollo iSCSI è disponibile solo per i volumi FlexVol. ^1^
* Per ogni volume è possibile configurare una sola LUN.




== Protezione dei dati

* Impossibile eliminare gli snapshot.
* Quando si replica un file system, tutti i volumi del file system utilizzano la stessa policy di replica.
* Per le relazioni di replica con conservazione a lungo termine, solo l'ultimo snapshot è disponibile per il ripristino.
* Le seguenti funzioni non sono supportate con gli snapshot immutabili:
+
** Gruppi di coerenza
** FabricPool
** Volumi FlexCache
** SMtape
** Sincronizzazione attiva di SnapMirror
** Regole dei criteri SnapMirror che utilizzano il parametro -Schedule
** SnapMirror sincrono
** Mobilità dei dati delle SVM (utilizzata per la migrazione o il trasferimento di una SVM da un cluster di origine a un cluster di destinazione)






== Calcolatore del risparmio dello storage

Il calcolatore di risparmio dello storage non calcola il risparmio sui costi per le seguenti configurazioni:

* FSX per Windows file Server: Tipo di storage HDD
* Elastic Block Store (EBS): Tipi di volume ST1, SC1 e standard
* Elastic file System (EFS): Modalità di throughput di bursting




== System Manager

Gestione sistema non supporta i collegamenti per la connettività di FSX per ONTAP.



== Supporto di AWS Secrets Manager

AWS Secrets Manager non è supportato quando si utilizza un agente Console.

Nota:

. Si applica ad Amazon FSX per NetApp ONTAP

