---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: 'Amazon FSX per NetApp ONTAP è un servizio completamente gestito che consente ai clienti di avviare ed eseguire i file system come back-end di storage per i carichi di lavoro all"interno di una fabbrica di workload.' 
---
= Scopri Amazon FSX per NetApp ONTAP in una fabbrica di workload BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSX per NetApp ONTAP è un servizio di storage dei dati basato sul cloud e completamente gestito che offre capacità di gestione dei dati avanzate e performance altamente scalabili. FSX per ONTAP ti permette di creare e gestire i file system come back-end dello storage per tutti i tuoi workload all'interno di una farm di workload BlueXP .

FSX per ONTAP offre le stesse funzionalità, performance e funzionalità amministrative che i clienti NetApp utilizzano on-premise oggi, con la semplicità, l'agilità, la sicurezza e la scalabilità di un servizio AWS nativo.

FSX per ONTAP è il componente _storage_ in una fabbrica di carichi di lavoro.



== Caratteristiche

FSX per ONTAP offre le seguenti caratteristiche:

* *Servizio completamente gestito*: Fornisce un servizio completamente gestito integrato con la console workload Factory.
* *Alta disponibilità*: Offre un'elevata disponibilità per ogni file system FSX per ONTAP, supportando implementazioni di zone di disponibilità singole e multiple.
* *Istantanee automatizzate*: Protegge i dati con istantanee efficienti e automatizzate, ovvero copie di sola lettura point-in-time, quasi istantanee ed efficienti in termini di spazio, del file system o dei volumi.
* *Volume Replication*: Offre funzioni di disaster recovery con replica tra più aree su Amazon Web Services.
* *Backup efficienti*: Aggiunge un ulteriore livello di protezione con una copia dei dati in un'altra regione per le emergenze.
* *Clonazione rapida*: Accelera lo sviluppo di applicazioni grazie alla clonazione rapida.
* *Supporto multiprotocollo*: Supporta i protocolli NFS (Network file System), SMB (Server message Block) e iSCSI (Internet Small computer Systems Interface).
* *Throughput elevato*: Offre prestazioni con throughput elevato per garantire latenze basse per i carichi di lavoro in esecuzione su file system FSX per ONTAP.
* *Cache in memoria e cache NVMe*: Includono una cache in-memory univoca e una cache NVMe, che migliorano le performance dei dati ad accesso frequente.
* *Centinaia di migliaia di IOPS*: Fornisce centinaia di migliaia di IOPS con dischi SSD, garantendo che storage e carichi di lavoro ricevano risultati tempestivi.
* *Thin Provisioning*: Consente il provisioning della capacità in anticipo, risparmiando sui costi fino a quando non è necessaria una maggiore capacità.
* *Deduplicazione e compressione dei dati*: Rimuove i dati duplicati e comprime i dati per ridurre la quantità di storage fisico necessaria per FSX per i file system ONTAP, con conseguenti risparmi sui costi.
* *Data tiering*: Consente di ridurre i costi di storage spostando i dati a cui si accede meno frequentemente dal livello di storage SSD primario e ad alte prestazioni al livello di storage del pool di capacità secondario.




== Funzionalità aggiuntive in workload factory

* *Calcolatore di confronto dei costi di storage*: Confronta i costi di storage di Amazon Elastic Block Store (EBS), Elastic file System (EFS) e FSX per Windows file Server con FSX per ONTAP. Dal calcolatore, puoi visualizzare come le configurazioni storage di FSX per ONTAP offrono potenziali risparmi e pianificare il passaggio allo storage FSX per ONTAP.
* *Interfaccia utente di workload Factory*: Fornisce le opzioni di modalità di distribuzione _Quick create_ e _Advanced create_. La creazione rapida include AWS, NetApp e Best practice standard di settore per le tue configurazioni storage.
* *Codebox*: Fornisce agli sviluppatori un visualizzatore di codice per le operazioni FSX for ONTAP, modelli di codice per la copia e il download e un catalogo di automazione per il riutilizzo del codice.




== Strumenti per l'utilizzo di workload Factory

È possibile utilizzare la farm di workload BlueXP  con i seguenti tool:

* *Workload Factory Console*: La console workload Factory offre una visione visiva e olistica delle applicazioni e dei progetti.
* *Console BlueXP *: La console BlueXP  offre un'interfaccia ibrida in modo da poter utilizzare la fabbrica dei workload BlueXP  insieme ad altri servizi BlueXP .
* *Chiedimi*: Utilizza l'assistente Ask me ai per porre domande e saperne di più sulla fabbrica di workload senza abbandonare l'interfaccia utente web della fabbrica di workload. Accedere a Chiedimi dal menu della guida di fabbrica del carico di lavoro.
* *CLI CloudShell*: Workload Factory include una CLI CloudShell per gestire e utilizzare ambienti AWS e NetApp tra diversi account da un'unica CLI basata su browser. Accedi a CloudShell dalla barra superiore della console workload Factory.
* *API REST*: Utilizza le API REST DI workload factory per implementare e gestire i file system FSX per ONTAP e altre risorse AWS.
* *CloudFormation*: Utilizzare il codice AWS CloudFormation per eseguire le azioni definite nella console workload factory in modo da modellare, eseguire il provisioning e gestire risorse AWS e di terze parti dallo stack CloudFormation nell'account AWS.
* *Terraform BlueXP  workload Factory Provider*: USA Terraform per costruire e gestire i flussi di lavoro infrastrutturali generati nella console di workload Factory.




== Costo

AWS gestisce il tuo account FSX per ONTAP, non la fabbrica di workload. Fare riferimento alla link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Prezzi di Amazon FSX per NetApp ONTAP"^].



== Regioni

Workload Factory è supportato in tutte le regioni commerciali in cui è supportato FSx per ONTAP .link:https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Visualizza le regioni Amazon supportate."^]

Le seguenti regioni AWS non sono supportate:

* regioni della Cina
* Regioni GovCloud (USA)
* Nuvola segreta
* Nuvola top secret




== Assistenza

Amazon FSX per NetApp ONTAP è una soluzione AWS first-party. Per domande o problemi di supporto tecnico associati al file system, all'infrastruttura o alla soluzione FSX per ONTAP che utilizza questo servizio, utilizza il Support Center nella console di gestione AWS per aprire un caso di supporto con AWS. Selezionare il servizio "FSX per ONTAP" e la categoria appropriata. Fornire le informazioni rimanenti necessarie per creare il caso di supporto AWS.

Per domande generali sulle applicazioni e i servizi di fabbrica dei carichi di lavoro o di fabbrica dei carichi di lavoro, fare riferimento a link:get-help.html["Scopri FSX per ONTAP per la fabbrica di workload"].
