---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Un collegamento Workload Factory crea una relazione di trust e connettività tra un account Workload Factory e uno o più file system FSx for ONTAP . 
---
= Scopri i link di NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un collegamento NetApp Workload Factory crea una relazione di trust e connettività tra un account Workload Factory e uno o più file system FSx for ONTAP .  Ciò consente di monitorare e gestire determinate funzionalità del file system direttamente dalle chiamate API REST ONTAP che non sono disponibili tramite l'API Amazon FSx for ONTAP .

Per iniziare a usare Workload Factory non è necessario un collegamento, ma in alcuni casi sarà necessario crearne uno per sbloccare tutte le funzionalità di Workload Factory e le capacità del carico di lavoro.



== Perché i link sono utili

I collegamenti sono utili perché consentono a Workload Factory di eseguire operazioni che non sono disponibili in modo nativo tramite l'API Amazon FSx for ONTAP .  I collegamenti abilitano funzionalità e automazioni ONTAP avanzate, che migliorano la gestione dei file system FSx per ONTAP .

Ecco alcuni vantaggi derivanti dall'utilizzo dei link:

* Il collegamento consente alla console NetApp di inviare comandi ONTAP direttamente al file system FSx for ONTAP , offrendo funzionalità ONTAP avanzate che vanno oltre ciò che AWS offre in modo nativo.
* I collegamenti sfruttano AWS Lambda per eseguire codice in risposta agli eventi. Questo approccio serverless elimina la dipendenza da un'istanza in esecuzione nella tua VPC.




== Come funzionano i collegamenti

I link sfruttano AWS Lambda. Lambda esegue il codice in risposta agli eventi e gestisce automaticamente le risorse di elaborazione richieste da tale codice. I link creati fanno parte del tuo account NetApp e sono associati a un account AWS.

Dopo aver creato un collegamento, è possibile associarlo a uno o più file system FSx per ONTAP . Ogni file system può essere associato a un solo collegamento nello stesso account NetApp. Se si dispone di più account NetApp, è possibile associare un singolo file system a collegamenti aggiuntivi in diversi account NetApp.

È possibile creare e associare collegamenti dal carico di lavoro di archiviazione in Workload Factory.

È possibile autenticare i collegamenti utilizzando le credenziali archiviate nel servizio credenziali Workload Factory oppure con le credenziali archiviate in AWS Secrets Manager.  Workload Factory non supporta la modifica delle modalità di autenticazione.



== Costi

Ogni transazione eseguita da Lambda comporta un costo.  Poiché Lambda funge da proxy tra i due sistemi, viene addebitato un costo quando Lambda invia una richiesta all'API REST ONTAP su un file system e quando invia la risposta a Workload Factory.

link:https://aws.amazon.com/lambda/pricing/["Scopri di più sui costi legati all'utilizzo di AWS Lambda"^]



== Quando è necessario un collegamento

La fabbrica del carico di lavoro necessita di un collegamento per visualizzare alcune informazioni ed eseguire alcune attività.  Se si tenta di eseguire un'operazione che richiede un collegamento e non è stato associato un collegamento al file system FSx for ONTAP , Workload Factory avvisa che l'operazione richiede un collegamento.

Le funzioni che richiedono un collegamento includono:

* Stato ben progettato delle configurazioni del file system FSx per ONTAP per manutenzione proattiva, affidabilità e ottimizzazione dei costi-prestazioni
* Protezione autonoma da ransomware NetApp (ARP/AI)
* Miglioramento dell'osservabilità olistica della capacità su FSx per i file system ONTAP
* Replicazione, gestione e monitoraggio dei dati VM di volume e storage
* Provisioning e gestione delle condivisioni SMB/CIFS e delle policy di esportazione NFS
* Gestione dei volumi iSCSI in un file system FSX per ONTAP
* Creazione e gestione di policy snapshot per SLA di protezione personalizzati
* Miglioramenti nella gestione degli inode per la gestione automatica della capacità
* Aumento automatico del volume per il ridimensionamento elastico
* Creazione e gestione di cloni, per la clonazione istantanea dei dati sul posto
* Visualizzazione di metriche aggiuntive direttamente da ONTAP , come la versione ONTAP


Informazioni su link:create-link.html["collegare un collegamento a un file system FSx per ONTAP"].
