---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Un collegamento in fabbrica dei carichi di lavoro crea una relazione di fiducia e connettività tra un account workload Factory e uno o più file system FSX per ONTAP. 
---
= Scopri di più sui collegamenti alla BlueXP  workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un collegamento alla fabbrica dei carichi di lavoro BlueXP  crea una relazione di fiducia e connettività tra un account workload Factory e uno o più file system FSX per ONTAP. Ciò ti consente di monitorare e gestire determinate funzionalità del file system direttamente dalle chiamate delle API REST di ONTAP che non sono disponibili tramite l'API Amazon FSX per ONTAP.

Non è necessario un collegamento per iniziare con la fabbrica dei carichi di lavoro, ma in alcuni casi è necessario creare un collegamento per sbloccare tutte le funzioni di fabbrica dei carichi di lavoro e le capacità dei carichi di lavoro.



== Come funzionano i collegamenti

I link sfruttano AWS Lambda. Lambda esegue il codice in risposta agli eventi e gestisce automaticamente le risorse di elaborazione richieste da tale codice. I link creati fanno parte del tuo account NetApp e sono associati a un account AWS.

Dopo aver creato un collegamento, è possibile associarlo a uno o più file system FSX per ONTAP. Ogni file system può essere associato a un solo collegamento nello stesso account NetApp. Se si dispone di più account NetApp, è possibile associare un singolo file system a collegamenti aggiuntivi in diversi account NetApp.

Vengono creati collegamenti dalle pagine del file system FSX per ONTAP in workload factory. link:create-link.html["Informazioni su come creare collegamenti"] per ulteriori informazioni.

Puoi creare link autentici utilizzando le credenziali memorizzate nel servizio delle credenziali in fabbrica del workload o con le tue credenziali memorizzate in AWS Secrets Manager. Workload Factory non supporta la modifica delle modalità di autenticazione.



== Costi

Ogni transazione eseguita da Lambda comporta un addebito. Poiché Lambda agisce come proxy tra i due sistemi, quando Lambda invia una richiesta all'API REST ONTAP su un file system e quando invia la risposta a una fabbrica dei carichi di lavoro viene addebitato un costo.

link:https://aws.amazon.com/lambda/pricing/["Scopri di più sui costi legati all'utilizzo di AWS Lambda"^]



== Quando è necessario un collegamento

Workload Factory richiede un collegamento per visualizzare alcune informazioni ed eseguire alcune attività. Se si tenta di eseguire un'operazione che richiede un collegamento e non è stato associato un collegamento al file system FSX per ONTAP, viene visualizzato un messaggio che informa che l'operazione richiede un collegamento. È possibile aggiungere un nuovo collegamento o associare il file system FSX per ONTAP a un collegamento esistente in quel momento, in modo da poter eseguire l'operazione.

Le funzioni che richiedono un collegamento includono:

* Visualizzazione della versione di ONTAP installata su un file system FSX per ONTAP
* Gestione dei volumi iSCSI in un file system FSX per ONTAP
* Funzione di crescita automatica dei volumi
* Creazione e gestione di policy di snapshot
* Configurazione delle relazioni di replica
* Replica di un volume tra file system FSX per ONTAP
* Configurazione della relazione di backup
* Backup dei dati nel cloud storage
* Cloni di volumi in un file system FSX per ONTAP
* Visualizzazione di metriche aggiuntive direttamente da ONTAP (le metriche predefinite vengono raccolte da Amazon CloudWatch)
* Gestione delle policy di esportazione NFS
* Gestione delle condivisioni CIFS

