---
sidebar: sidebar 
permalink: manage-svm-tags.html 
keywords: edit storage vm tags, vm tags, svm tags 
summary: Aggiunta, aggiornamento o rimozione dei tag delle macchine virtuali di storage per una macchina virtuale di storage in qualsiasi momento. 
---
= Gestisci i tag delle VM di archiviazione in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
I tag possono aiutarti a categorizzare le tue risorse.  È possibile aggiungere, modificare e rimuovere i tag per una VM di storage in qualsiasi momento in NetApp Workload Factory.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system con la VM di archiviazione da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Dalla scheda VM di archiviazione, seleziona il menu delle azioni della VM di archiviazione per cui modificare i tag.
. Selezionare *Modifica tag VM di archiviazione*.
. Nella pagina Modifica tag VM di archiviazione, aggiungere, modificare o rimuovere tag.
+
Il numero massimo di tag che puoi applicare a una macchina virtuale di storage è 50.

. Selezionare *Applica*.

