---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, smb, SMB/CIFS, cifs share, change, update, modify, delete, create 
summary: 'La gestione della condivisione SMB/CIFS di un volume nella fabbrica dei carichi di lavoro include la creazione, la determinazione dell"accesso di utenti e gruppi e l"eliminazione.' 
---
= Gestire la condivisione SMB/CIFS per un volume nella fabbrica del carico di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La gestione della condivisione SMB/CIFS di un volume in Workload Factory include la creazione della condivisione SMB/CIFS, la determinazione degli utenti e dei gruppi a cui concedere l'accesso e del livello di autorizzazioni da concedere loro, nonché l'eliminazione della condivisione SMB/CIFS.

.Prima di iniziare
Prima di iniziare, effettuare le seguenti operazioni:

* Per gestire le condivisioni SMB/CIFS, è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"] .  Dopo aver associato il collegamento, tornare a questa operazione.
* Determinare gli utenti o i gruppi a cui assegnare l'accesso e il livello di autorizzazioni da assegnare.




== Creare una condivisione SMB/CIFS per un volume

Seguire i passaggi per creare una condivisione SMB/CIFS per un volume.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system con il volume da aggiornare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda volumi, selezionare il menu a tre punti del volume per cui modificare la condivisione SMB.
. Selezionare *Azioni avanzate*, quindi *Gestisci condivisioni SMB/CIFS*.
. Nella pagina Gestisci condivisioni SMB/CIFS, seleziona *Crea condivisione SMB/CIFS*.
. Nella finestra di dialogo Crea condivisione SMB/CIFS, fornisci quanto segue:
+
.. *Nome*: immettere il nome della condivisione SMB/CIFS.
.. *Percorso*: definire il percorso utilizzando il nome del volume predefinito oppure fornire una condivisione in una directory interna.
+
I percorsi validi per il nome del volume, ad esempio "avocado", sono i seguenti:

+
*** /avocado
*** /avocado/cartella
*** /avocado/cartella/sottocartella
*** /avocado/nome-file
+
I percorsi validi per il nome della condivisione, ad esempio "Server", sono i seguenti:

*** \\Server
*** \\Server\Progetti
*** \\Server\Progetti\Risorse condivise


.. *Autorizzazioni*: Selezionare controllo completo, lettura/scrittura, lettura o Nessun accesso, quindi immettere gli utenti o i gruppi separati da un punto e virgola ( ; ). Gli utenti o i gruppi rilevano la distinzione tra maiuscole e minuscole e il dominio dell'utente deve essere incluso nel formato "dominio\nome utente".


. Selezionare *Crea*.




== Modificare una condivisione SMB/CIFS per un volume

Seguire i passaggi per modificare le impostazioni di condivisione SMB/CIFS per un volume.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system con il volume da aggiornare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda volumi, selezionare il menu a tre punti del volume per cui modificare la condivisione SMB.
. Selezionare *Azioni avanzate*, quindi *Gestisci condivisioni SMB/CIFS*.
. Nella pagina Gestisci condivisioni SMB/CIFS, seleziona *Visualizza e modifica*.
. Modificare le autorizzazioni di accesso SMB/CIFS oppure gli utenti o i gruppi a cui concedere le autorizzazioni.
+
Le modifiche potrebbero causare la perdita dell'accesso alla condivisione SMB/CIFS da parte degli utenti o dei gruppi attuali.

. Selezionare *Applica* per salvare le modifiche.




== Elimina una condivisione SMB/CIFS per un volume

Seguire i passaggi per eliminare una condivisione SMB/CIFS per un volume.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system con il volume da aggiornare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda volumi, selezionare il menu a tre punti del volume per cui modificare la condivisione SMB.
. Selezionare *Azioni avanzate*, quindi *Gestisci condivisioni SMB/CIFS*.
. Nella pagina Gestisci condivisioni SMB/CIFS, seleziona il menu a tre punti della condivisione SMB/CIFS, quindi seleziona *Elimina*.
+
L'eliminazione della condivisione SMB/CIFS la rende non disponibile e inaccessibile a tutti gli utenti che desiderano montarla.

. Nella finestra di dialogo Elimina condivisione SMB/CIFS, selezionare *Elimina* per confermare l'eliminazione.

