---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, CIFS, cifs share, change cifs share, update cifs share, modify cifs share 
summary: Modifica della CIFS share per un volume nella fabbrica del carico di lavoro BlueXP  che utilizza il tipo di protocollo SMB/CIFS. 
---
= Gestione della CIFS share per un volume in una fabbrica di carichi di lavoro BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La gestione della CIFS share di un volume nella fabbrica di carichi di lavoro BlueXP  implica l'individuazione degli utenti e dei gruppi ai quali assegnare l'accesso e del tipo di accesso.

.Prima di iniziare
Determinare gli utenti o i gruppi a cui concedere l'accesso e il tipo di accesso a cui concedere l'accesso.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system con il volume da aggiornare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda volumi, selezionare il menu a tre punti del volume per cui modificare la condivisione SMB.
. Selezionare *azioni avanzate*, quindi *Modifica condivisione CIFS*.
. Nella pagina Edit CIFS share (Modifica condivisione CIFS), specificare quanto segue:
+
.. *Nome*: Immettere il nome della condivisione CIFS.
.. *Autorizzazioni*: Selezionare controllo completo, lettura/scrittura, lettura o Nessun accesso, quindi immettere gli utenti o i gruppi separati da un punto e virgola ( ; ). Gli utenti o i gruppi rilevano la distinzione tra maiuscole e minuscole e il dominio dell'utente deve essere incluso nel formato "dominio\nome utente".


. Selezionare Apply (Applica).
+
Eventuali modifiche possono causare la perdita dell'accesso alla condivisione CIFS da parte di utenti o gruppi correnti.

. Selezionare *continua* per salvare le modifiche.


.Risultato
Vengono applicate le modifiche alla condivisione CIFS.
