---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: Gestire i criteri di snapshot per i volumi FSx for ONTAP in Workload Factory.  Un criterio di snapshot definisce il modo in cui il sistema crea snapshot per un volume. 
---
= Gestire le policy delle snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Gestire i criteri di snapshot per i volumi FSx for ONTAP in Workload Factory.  Un criterio di snapshot definisce il modo in cui il sistema crea snapshot per un volume.

.A proposito di questa attività
Le operazioni di gestione di Snapshot, come l'assegnazione, la modifica e l'eliminazione delle policy di Snapshot per i volumi in un file system FSX per ONTAP, vengono gestite a livello di VM di storage. Le policy di Snapshot possono essere condivise con una singola macchina virtuale storage o con tutte le macchine virtuali storage.

Alcune attività di gestione richiedono l'associazione di un collegamento al file system FSx for ONTAP . link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Scopri di più sui link di Workload Factory"] .

Per impostazione predefinita, ogni volume è associato al criterio di snapshot del file system `default` . Consigliamo di utilizzare questa policy per la maggior parte dei carichi di lavoro.



== Modificare una policy di snapshot

È possibile modificare il nome del criterio snapshot, la pianificazione e il numero di copie da conservare e attivare o disattivare gli snapshot immutabili. Non è possibile attivare o disattivare la condivisione dei criteri tra le VM di storage. Questa opzione è disponibile solo durante la creazione dei criteri di snapshot.

.Prima di iniziare
Per visualizzare i criteri di snapshot esistenti, è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. In *Archiviazione*, seleziona *Vai ad Archiviazione*.
. Nella scheda *FSx per ONTAP*, selezionare il menu azioni del file system e quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Dalla scheda *VM di archiviazione*, seleziona il menu delle azioni per la VM di archiviazione contenente il volume da proteggere con snapshot pianificati, quindi *Azioni avanzate* e infine *Gestisci criteri snapshot*.
. Nella pagina di gestione dei criteri di snapshot, seleziona il menu delle azioni per modificare il criterio di snapshot, quindi seleziona *Modifica*.
. Nella finestra di dialogo Modifica criterio snapshot, apportare le modifiche necessarie al criterio snapshot.
. Selezionare *Applica*.


.Risultato
Il criterio snapshot viene aggiornato.



== Attiva gli snapshot immutabili

Bloccare gli snapshot per impedirne l'eliminazione durante il periodo di conservazione.

.Prima di iniziare
Per abilitare gli snapshot immutabili è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. In *Archiviazione*, seleziona *Vai ad Archiviazione*.
. Nella scheda *FSx per ONTAP*, selezionare il menu azioni del file system che contiene il volume per cui bloccare gli snapshot, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda *Volumi*, selezionare l'azione relativa al volume da proteggere.
. Selezionare *azioni protezione dati*, *istantanee*, quindi *Rendi immutabile uno snapshot*.
. Nella finestra di dialogo Rendi un'istantanea immutabile, effettuare le seguenti operazioni:
+
.. *Nome istantanea*: Selezionare l'istantanea da bloccare.
.. Impostare *periodo di conservazione* in numero di ore, giorni, mesi o anni.
.. Accettare la dichiarazione.


. Selezionare *Applica*.


.Risultato
Lo snapshot del volume è ora bloccato.



== Assegnare un criterio snapshot a un volume

È possibile assegnare una policy di snapshot a un singolo volume per creare snapshot pianificate per il volume.

.Prima di iniziare
È necessario associare un collegamento per assegnare un criterio di snapshot. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. In *Archiviazione*, seleziona *Vai ad Archiviazione*.
. Nella scheda *FSx per ONTAP*, selezionare il menu azioni del file system che contiene il volume a cui assegnare un criterio snapshot, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Dalla scheda *VM di archiviazione*, seleziona il menu delle azioni per la VM di archiviazione contenente il volume da proteggere con snapshot pianificati, quindi *Azioni avanzate* e infine *Gestisci criteri snapshot*.
. Nella pagina di gestione dei criteri di snapshot, selezionare il menu delle azioni del criterio di snapshot, quindi selezionare *Assegna criterio al volume*.
. Nella finestra di dialogo Assegna criterio snapshot, selezionare un criterio snapshot da assegnare al volume ed esaminare la pianificazione dei criteri.
+
Se il criterio contiene istantanee immutabili e si desidera utilizzarlo, accettare l'istruzione.

. Selezionare *Assegna*.


.Risultato
Il criterio snapshot viene assegnato al volume.



== Rimozione di un criterio di snapshot da un volume

Rimozione di una policy di snapshot da un volume perché non si desidera più creare snapshot del volume o perché si desidera eliminare una policy di snapshot assegnata a più volumi. A <<Eliminazione di una policy di snapshot,eliminazione di una policy di snapshot>> questo viene assegnato più di un volume, è necessario rimuoverlo manualmente da tutti i volumi.

.Prima di iniziare
Per rimuovere un criterio di snapshot è necessario associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo l'associazione del collegamento, tornare a questa operazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. In *Archiviazione*, seleziona *Vai ad Archiviazione*.
. Nella scheda *FSx per ONTAP*, selezionare il menu azioni del file system che contiene il volume a cui assegnare un criterio snapshot, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Dalla scheda *VM di archiviazione*, seleziona il menu delle azioni per la VM di archiviazione contenente il volume da proteggere con snapshot pianificati, quindi *Azioni avanzate* e infine *Gestisci criteri snapshot*.
. Nella pagina di gestione dei criteri di snapshot, selezionare il menu delle azioni del criterio di snapshot, quindi selezionare *Assegna criterio al volume*.
. Nella finestra di dialogo Assegna criterio snapshot, selezionare *Nessuno* per rimuovere il criterio snapshot.
. Selezionare *Assegna*.


.Risultato
Il criterio di snapshot viene rimosso dal volume.



== Eliminazione di una policy di snapshot

Elimina una policy di snapshot quando non è più necessaria.

Quando un criterio snapshot viene assegnato a più volumi, è necessario eliminarlo manualmente <<Rimozione di un criterio di snapshot da un volume,rimuoverlo>> da tutti i volumi. In alternativa, è possibile <<Assegnare un criterio snapshot a un volume,assegnare un criterio di snapshot diverso>> accedere ai volumi.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. In *Archiviazione*, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system con il volume e quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Storage VM*.
. Dalla scheda *VM di archiviazione*, seleziona il menu azioni della VM di archiviazione con il criterio snapshot da eliminare, quindi *Azioni avanzate* e infine *Gestisci criteri snapshot*.
. Nella pagina di gestione dei criteri di snapshot, seleziona il menu delle azioni per il criterio di snapshot da eliminare, quindi seleziona *Elimina*.
. Nella finestra di dialogo Elimina, selezionare *Elimina* per eliminare il criterio.

