---
sidebar: sidebar 
permalink: manage-cache-volumes.html 
keywords: cache volumes, manage cache, FSx for ONTAP cache 
summary: Gestire i volumi di cache per un file system FSx for ONTAP in NetApp Workload Factory quando necessario. 
---
= Gestisci i volumi di cache FSx for ONTAP con NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Utilizzare la console NetApp Workload Factory per gestire i volumi di cache per i file system FSx for ONTAP .  La memorizzazione nella cache, un metodo per l'archiviazione temporanea dei dati, migliora le prestazioni di accesso ai dati riducendo i tempi di recupero.  È possibile modificare il nome della cache, regolarne la capacità, cambiare i criteri di esportazione, selezionare un metodo di memorizzazione nella cache, precompilare la cache o eliminare i volumi della cache.

.A proposito di questa attività
È possibile gestire i volumi di cache associati alle relazioni di cache nella console NetApp Workload Factory .

.Prima di iniziare
* È necessario associare un collegamento per gestire i volumi e le relazioni della cache. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o come creare e associare un nuovo collegamento"]. Dopo aver associato il collegamento, tornare a questa operazione.
* Per modificare è necessario disporre di un volume di cache esistente.




== Modifica il nome del volume della cache

È possibile modificare il nome di un volume di cache esistente in qualsiasi momento.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare FSx per ONTAP.
. Da FSx per ONTAP, selezionare il menu azioni del file system con il volume della cache, quindi selezionare *Gestisci*.
. Dalla panoramica del file system, seleziona la scheda *Relazioni cache*.
. Selezionare il menu azioni per il volume della cache che si desidera modificare, quindi selezionare *Modifica nome cache*.
. Nella finestra di dialogo *Modifica nome cache*, immettere il nuovo nome per il volume della cache e quindi selezionare *Applica*.




== Regola la capacità di un volume di cache

È possibile modificare la capacità di un volume di cache esistente in qualsiasi momento.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare FSx per ONTAP.
. Da FSx per ONTAP, selezionare il menu azioni del file system con il volume della cache, quindi selezionare *Gestisci*.
. Dalla panoramica del file system, seleziona la scheda *Relazioni cache*.
. Selezionare il menu azioni per il volume della cache che si desidera modificare, quindi selezionare *Regola capacità cache*.
. Nella finestra di dialogo *Regola capacità cache*, immettere la nuova capacità per il volume della cache in percentuale o in unità, quindi selezionare *Applica*.




== Modifica la politica di esportazione del volume della cache

Modificare il percorso di montaggio o la policy di esportazione assegnata a un volume di cache esistente.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare FSx per ONTAP.
. Da FSx per ONTAP, selezionare il menu azioni del file system con il volume della cache, quindi selezionare *Gestisci*.
. Dalla panoramica del file system, seleziona la scheda *Relazioni cache*.
. Selezionare il menu azioni per il volume di cache che si desidera modificare, quindi selezionare *Modifica criterio di esportazione*.
. Nella finestra di dialogo *Modifica criterio di esportazione*, modifica il percorso di montaggio o seleziona un criterio di esportazione diverso da assegnare al volume della cache.
. Selezionare *Applica*.




== Modificare il metodo di memorizzazione nella cache per un volume di cache

È possibile modificare il funzionamento della cache per un volume di cache esistente, scegliendo tra write-around o write-back.

Scopri di più sulink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/using-flexcache.html["modalità di scrittura"^] .

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare FSx per ONTAP.
. Da FSx per ONTAP, selezionare il menu azioni del file system con il volume della cache, quindi selezionare *Gestisci*.
. Dalla panoramica del file system, seleziona la scheda *Relazioni cache*.
. Selezionare il menu azioni per il volume di cache che si desidera modificare, quindi selezionare *Cambia metodo di memorizzazione nella cache*.
. Nella finestra di dialogo *Modifica metodo di memorizzazione nella cache*, seleziona il nuovo metodo di memorizzazione nella cache e poi seleziona *Applica*.




== Precompilare un volume di cache

Riempi il volume della cache con i dati del volume di origine prima di utilizzarlo per rendere i dati memorizzati nella cache disponibili più rapidamente.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare FSx per ONTAP.
. Da FSx per ONTAP, selezionare il menu azioni del file system con il volume della cache, quindi selezionare *Gestisci*.
. Dalla panoramica del file system, seleziona la scheda *Relazioni cache*.
. Selezionare il menu azioni per il volume della cache che si desidera modificare, quindi selezionare *Prepopola cache*.
. Nella finestra di dialogo *Prepopola cache*, specificare il percorso del set di dati da utilizzare per il prepopolamento, quindi selezionare *Applica*.




== Elimina un volume di cache

Quando si elimina un volume di cache, si rimuove la relativa relazione con la cache.  I dati memorizzati nella cache non sono più disponibili.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare FSx per ONTAP.
. Da FSx per ONTAP, selezionare il menu azioni del file system con il volume della cache, quindi selezionare *Gestisci*.
. Dalla panoramica del file system, seleziona la scheda *Relazioni cache*.
. Selezionare il menu azioni per il volume di cache che si desidera eliminare, quindi selezionare *Elimina volume di cache*.
. Nella finestra di dialogo *Elimina volume cache*, confermare l'eliminazione e quindi selezionare *Elimina*.

