---
sidebar: sidebar 
permalink: pause-resume-replication.html 
keywords: pause replication, quiesce replication, resume replication 
summary: Sospendere e riprendere una relazione di replica in modo che il volume di destinazione diventi il volume di origine. 
---
= Mettere in pausa e riprendere una relazione di replica in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Sospendere una relazione di replica per interrompere gli aggiornamenti pianificati delle repliche dal volume di origine al volume di destinazione. Il volume di destinazione passa da sola lettura a lettura/scrittura. Entrambi i volumi continuano a condividere l'ultimo snapshot di replica come nuova base per la risincronizzazione successiva.

.A proposito di questa attività
Quando è in pausa, la relazione di replica tra il volume di origine e quello di destinazione continua a esistere. I trasferimenti di dati si interrompono e i volumi diventano indipendenti. Per riattivare il trasferimento delle modifiche dal volume di origine al volume di destinazione, riprendere la replica.

Quando si riprende una replica, tutte le modifiche apportate al volume di destinazione vengono annullate e NetApp Workload Factory riattiva la replica.  Il volume di destinazione passa dalla modalità di lettura/scrittura a quella di sola lettura e riceve nuovamente gli aggiornamenti dal volume di origine all'intervallo di replica pianificato.  Quando si riprende una relazione di replica, il volume di destinazione torna all'ultimo snapshot di replica iniziale, a quel punto il processo di replica del volume ricomincia.

.Prima di iniziare
Se si effettua una pausa quando un trasferimento è in corso, il trasferimento non viene influenzato e la relazione diventa "Esci" fino al completamento del trasferimento. Se il trasferimento corrente viene interrotto, si tratta di un trasferimento futuro e non viene riavviato.



== Sospensione di una relazione di replica

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Relazioni di replica*.
. Nella scheda Relazioni di replicazione, selezionare il menu delle azioni della relazione di replicazione da sospendere.
. Selezionare *Pausa (Quiesce)*.
. Nella finestra di dialogo *Quiesce Relationship*, selezionare *Quiesce*.


.Risultato
La relazione viene sospesa e il suo stato viene visualizzato come "in pausa".



== Riprendere una relazione di replica in pausa

Quando si riprende una relazione di replica, tutte le modifiche apportate al volume di destinazione durante l'interruzione della replica vengono eliminate.


NOTE: Tutti i dati scritti nel volume di origine tra l'ultima replica dei dati e l'ora in cui il volume di origine è disattivato non vengono conservati.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Relazioni di replica*.
. Nella scheda Relazioni di replicazione, selezionare il menu delle azioni della relazione di replicazione da riprendere.
. Selezionare *Riprendi*.
. Nella finestra di dialogo Riprendi relazione, selezionare *Riprendi*.


.Risultato
La relazione riprende e il suo stato viene visualizzato come "replicato".
