---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione di Amazon FSX per NetApp ONTAP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Limitazioni note
      url: "/known-limitations.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più su Amazon FSX per NetApp ONTAP
      url: "/learn-fsx-ontap.html"
    - title: Avvio rapido
      url: "/quick-start.html"
    - title: Crea un file system FSX per ONTAP
      url: "/create-file-system.html"
  - title: USA Amazon FSX per NetApp ONTAP
    entries:
    - title: Scopri i risparmi
      url: "/explore-savings.html"
    - title: Utilizzare i collegamenti
      entries:
      - title: Scopri di più sui link
        url: "/links-overview.html"
      - title: Connettersi a un file system con un collegamento
        url: "/create-link.html"
      - title: Gestisci collegamenti
        url: "/manage-links.html"
    - title: Scopri e visualizza i volumi della cache
      url: "/discover-cache-volumes.html"
    - title: Gestire i volumi
      entries:
      - title: Creare un volume
        url: "/create-volume.html"
      - title: Accedi ai tuoi dati
        url: "/access-data.html"
    - title: Creare una VM di storage
      url: "/create-storage-vm.html"
    - title: Proteggi i tuoi dati
      entries:
      - title: Panoramica sulla protezione dei dati
        url: "/data-protection-overview.html"
      - title: Utilizzare gli snapshot
        entries:
        - title: Creare un'istantanea
          url: "/create-snapshot.html"
        - title: Creare un criterio di snapshot
          url: "/create-snapshot-policy.html"
        - title: Ripristinare un volume da uno snapshot
          url: "/restore-volume-from-snapshot.html"
      - title: Utilizzare i backup per l'archiviazione degli oggetti
        entries:
        - title: Creare un backup manuale
          url: "/create-backup.html"
        - title: Ripristinare un volume da un backup
          url: "/restore-from-backup.html"
      - title: Utilizzare la replicazione
        entries:
        - title: Creare una relazione di replica
          url: "/create-replication.html"
        - title: Inizializzare una relazione di replica
          url: "/initialize-replication.html"
      - title: Proteggi i dati con la protezione autonoma da ransomware
        url: "/ransomware-protection.html"
      - title: Clonare un volume
        url: "/clone-volume.html"
      - title: Utilizzo dei dati ONTAP on-premise
        url: "/use-onprem-data.html"
      - title: Crea un caveau informatico per proteggere i dati
        url: "/create-cyber-vault.html"
  - title: Amministrare e monitorare
    entries:
    - title: Monitoraggio delle operazioni con Tracker
      url: "/monitor-operations.html"
    - title: Implementare le Best practice del file system
      entries:
      - title: Analisi della configurazione di FSX per ONTAP
        url: "/configuration-analysis.html"
      - title: Implementa configurazioni del file system con un'architettura ottimale
        url: "/improve-configurations.html"
    - title: Amministrazione dei volumi
      entries:
      - title: Consente di modificare la crescita automatica del volume
        url: "/edit-volume-autogrow.html"
      - title: Regola la capacità del volume
        url: "/adjust-volume-capacity.html"
      - title: Riequilibrare la capacità del volume
        url: "/rebalance-volume.html"
      - title: Gestire i file immutabili
        url: "/manage-immutable-files.html"
      - title: Gestire i tag di volume
        url: "/manage-volume-tags.html"
      - title: Gestisci i volumi della cache
        url: "/manage-cache-volumes.html"
      - title: Modificare una policy di tiering
        url: "/change-tiering-policy.html"
      - title: Update dell'efficienza dello storage
        url: "/update-storage-efficiency.html"
      - title: Gestire le policy di esportazione NFS
        url: "/manage-nfs-export-policy.html"
      - title: Gestire le condivisioni SMB/CIFS
        url: "/manage-cifs-share.html"
      - title: Divisione di un volume clonato
        url: "/split-cloned-volume.html"
      - title: Eliminare un volume
        url: "/delete-volume.html"
    - title: Amministrazione del file system
      entries:
      - title: Regola la capacità del file system
        url: "/increase-file-system-capacity.html"
      - title: Abilita la gestione automatica della capacità e degli inode
        url: "/enable-auto-capacity-management.html"
      - title: Reimpostare la password fsxadmin
        url: "/reset-fsxadmin-password.html"
      - title: Eliminare un file system
        url: "/delete-file-system.html"
    - title: Amministrazione delle macchine virtuali dello storage
      entries:
      - title: Replica di una macchina virtuale di storage su un altro file system
        url: "/replicate-svm-to-file-system.html"
      - title: Configurazione e aggiornamento di Active Directory per una macchina
          virtuale di storage
        url: "/configure-active-directory.html"
      - title: Gestire i tag delle VM di storage
        url: "/manage-svm-tags.html"
      - title: Reimpostare la password della VM di archiviazione
        url: "/reset-svm-password.html"
      - title: Eliminare una VM di storage
        url: "/delete-svm.html"
    - title: Amministrazione della protezione dei dati
      entries:
      - title: Snapshot
        entries:
        - title: Gestire le policy delle snapshot
          url: "/manage-snapshot-policy.html"
        - title: Abilita e modifica le snapshot per la conservazione a lungo termine
          url: "/enable-snapshots-long-term.html"
        - title: Gestione delle snapshot
          url: "/manage-snapshots.html"
      - title: Backup
        entries:
        - title: Gestire la pianificazione del backup di FSX per ONTAP
          url: "/manage-backup-schedule.html"
      - title: Replica
        entries:
        - title: Replica di un volume di data Protection
          url: "/cascade-replication.html"
        - title: Invertire una relazione di replica
          url: "/reverse-replication.html"
        - title: Consente di modificare la pianificazione della replica di un volume
            di origine
          url: "/change-replication-schedule.html"
        - title: Limitare la velocità di trasferimento massima di una relazione di
            replica
          url: "/limit-transfer-rate.html"
        - title: Aggiornamento manuale dei dati snapshot in una relazione di replica
          url: "/update-snapshot-replication.html"
        - title: Sospendere e riprendere una relazione di replica
          url: "/pause-resume-replication.html"
        - title: Interruzione di una relazione di replica
          url: "/stop-replication.html"
        - title: Eliminare una relazione di replica
          url: "/delete-replication.html"
    - title: Amministrazione delle prestazioni
      entries:
      - title: Provisioning degli IOPS per un file system
        url: "/provision-iops.html"
      - title: Aggiornare la capacità di throughput per un file system
        url: "/update-throughput-capacity.html"
  - title: Riferimento
    entries:
    - title: Performance di FSX per ONTAP
      url: "/performance-reference.html"
    - title: Sicurezza per FSX per ONTAP
      url: "/security-reference.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/support-registration.html"
    - title: Richiedi assistenza
      url: "/get-help.html"
    - title: Risoluzione dei problemi
      url: "/troubleshooting.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
