---
sidebar: sidebar 
permalink: provision-iops.html 
keywords: iops, SSD, provision, allocate 
summary: Esegui il provisioning automatico o manuale degli IOPS SSD per un file system FSX per ONTAP. 
---
= Esegui il provisioning di IOPS SSD per un file system FSX per ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Esegui il provisioning automatico o manuale di IOPS SSD per un file system FSx for ONTAP in NetApp Workload Factory.

.A proposito di questa attività
Puoi abilitare il provisioning IOPS automatico per un file system FSX oppure eseguire il provisioning manuale degli IOPS.

Gli IOPS con provisioning automatico vengono calcolati come tre IOPS per GiB.

Se si esegue il provisioning manuale degli IOPS, potrebbe essere necessario aumentare gli IOPS prima di link:increase-file-system-capacity.html["aumento della capacità del file system"].

Per informazioni sui limiti IOPS, fai riferimento alla link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Quote"^]documentazione di AWS FSX per NetApp ONTAP.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system per cui effettuare il provisioning degli IOPS, quindi seleziona *Gestisci*.
. Nella sezione informazioni, selezionare l'icona a forma di matita visualizzata accanto alla freccia del menu a discesa quando il mouse passa sopra la riga *allocazione IOPS*.
. Nella finestra di dialogo IOPS forniti, selezionare *automatico* o *fornito dall'utente*.
. Se si seleziona *provisioning utente*, immettere il valore *IOPS* desiderato.
. Selezionare *Applica*.

