---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Reimpostare la password per una VM di archiviazione in NetApp Workload Factory quando necessario. 
---
= Reimposta la password della VM di archiviazione in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Reimpostare la password per una VM di archiviazione in NetApp Workload Factory quando necessario.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Da Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system FSx for ONTAP con la VM di archiviazione da aggiornare, quindi selezionare *Gestisci*.
. Dalla scheda Panoramica del file system, selezionare la scheda *Storage VM*.
. Nella scheda VM di archiviazione, seleziona il menu delle azioni della VM di archiviazione per cui reimpostare la password.
. Selezionare *Ripristina password*.
. Nella finestra di dialogo Reimposta password, specificare quanto segue:
+
.. *Nuova password*: Inserire una nuova password per la VM di archiviazione.
.. *Conferma password*: Immettere nuovamente la nuova password per confermarla.


. Selezionare *Applica*.

