---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Se necessario, reimpostare la password per una macchina virtuale di storage in fabbrica con carico di lavoro BlueXP . 
---
= Reimpostare la password della macchina virtuale di archiviazione nella fabbrica del carico di lavoro BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Se necessario, reimpostare la password per una macchina virtuale di storage in fabbrica con carico di lavoro BlueXP .

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Da archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, seleziona il menu a tre punti del file system FSX per ONTAP con la VM di archiviazione da aggiornare, quindi seleziona *Gestisci*.
. Dalla scheda Panoramica del file system, selezionare la scheda *Storage VM*.
. Nella scheda Storage VM, selezionare il menu a tre punti della VM di storage per cui reimpostare la password.
. Selezionare *Ripristina password*.
. Nella finestra di dialogo Reimposta password, specificare quanto segue:
+
.. *Nuova password*: Inserire una nuova password per la VM di archiviazione.
.. *Conferma password*: Immettere nuovamente la nuova password per confermarla.


. Selezionare *Applica*.

