---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Reimpostare la password per una VM di archiviazione in NetApp Workload Factory quando necessario. 
---
= Reimposta la password della VM di archiviazione in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Reimpostare la password per una VM di archiviazione in NetApp Workload Factory quando necessario.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Da Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu azioni del file system con la password della VM di archiviazione da reimpostare, quindi seleziona *Gestisci*.
. Nella panoramica del file system in VM di archiviazione, selezionare *Gestisci*.
. Dalla schermata Gestisci VM di archiviazione, seleziona il menu delle azioni della VM di archiviazione per cui reimpostare la password, quindi seleziona *Azioni di base* > *Reimposta password*.
. Nella finestra di dialogo Reimposta password, specificare quanto segue:
+
.. *Nuova password*: Inserire una nuova password per la VM di archiviazione.
.. *Conferma password*: Immettere nuovamente la nuova password per confermarla.


. Selezionare *Applica*.

