---
sidebar: sidebar 
permalink: restore-from-backup.html 
keywords: restore backup, new volume, volume restoration, backup 
summary: Ripristina un volume da un backup in qualsiasi file system FSX per ONTAP nel tuo account AWS. 
---
= Ripristina un volume da un backup in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In NetApp Workload Factory, puoi ripristinare un volume da un backup su qualsiasi file system FSx for ONTAP nel tuo account AWS.

Workload Factory determina se si dispone di capacità sufficiente per il ripristino e, in caso contrario, può aggiungere automaticamente capacità del Tier di storage SSD.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system con il volume e quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda *Volumi*, selezionare il menu delle azioni per il volume da ripristinare da un backup.
. Selezionare *azioni protezione dati*, *FSX per il backup ONTAP*, quindi *Ripristina da un backup*.
. Nella finestra di dialogo Ripristina da un backup, specificare quanto segue:
+
.. *File system di destinazione*: Selezionare il file system di destinazione dal menu a discesa.
.. *VM di archiviazione di destinazione*: Selezionare la VM di archiviazione di destinazione dal menu a discesa.
.. *Nome backup*: Selezionare il nome del backup dal menu a discesa.
.. *Nome volume ripristinato*: Immettere il nome del volume ripristinato.


. Verificare la capacità del file system per l'operazione di ripristino.
+
Quando la capacità del file system è limitata, si possono verificare le seguenti condizioni:

+
** Il ripristino può spingere la capacità utilizzata oltre la soglia specificata.  È possibile completare l'operazione di ripristino.  Considerarelink:increase-file-system-capacity.html["Aggiunta manuale della capacità del Tier di storage SSD"] oppure selezionando Workload Factory per aggiungere automaticamente la capacità del livello di archiviazione SSD.
** Il ripristino richiede capacità SSD aggiuntiva.  Per procedere, è necessario selezionare Workload Factory per aggiungere automaticamente la capacità del livello di archiviazione SSD.


. Selezionare *Restore* (Ripristina).

