---
sidebar: sidebar 
permalink: restore-from-backup.html 
keywords: restore backup, new volume, volume restoration, backup 
summary: Ripristina un volume da un backup in qualsiasi file system FSX per ONTAP nel tuo account AWS. 
---
= Ripristino di un volume da un backup in una fabbrica di workload BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Nella fabbrica dei carichi di lavoro BlueXP , puoi ripristinare un volume da un backup su qualsiasi file system FSX per ONTAP nel tuo account AWS.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, selezionare il menu a tre punti del file system con il volume, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda *volumi*, selezionare il menu a tre punti per il volume da ripristinare da un backup.
. Selezionare *azioni protezione dati*, *FSX per il backup ONTAP*, quindi *Ripristina da un backup*.
. Nella finestra di dialogo Ripristina da un backup, specificare quanto segue:
+
.. *File system di destinazione*: Selezionare il file system di destinazione dal menu a discesa.
.. *VM di archiviazione di destinazione*: Selezionare la VM di archiviazione di destinazione dal menu a discesa.
.. *Nome backup*: Selezionare il nome del backup dal menu a discesa.
.. *Nome volume ripristinato*: Immettere il nome del volume ripristinato.


. Selezionare *Restore* (Ripristina).

