---
sidebar: sidebar 
permalink: restore-volume-from-snapshot.html 
keywords: restore volume, snapshot 
summary: Ripristinare un volume FSX per ONTAP da uno snapshot quando il volume contiene file eliminati o danneggiati. 
---
= Ripristina un volume da uno snapshot in Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In Workload Factory è possibile ripristinare i dati da uno snapshot a un volume esistente o a un nuovo volume. L'operazione di ripristino consente il recupero in un determinato momento quando un volume contiene file eliminati o danneggiati.

.A proposito di questa attività
È possibile ripristinare i dati da uno snapshot su un volume esistente o su un nuovo volume.

La creazione di un nuovo volume da uno snapshot crea una copia di un intero volume in pochi secondi, indipendentemente dalle dimensioni del volume.  La copia appena creata rappresenta un nuovo volume.

.Prima di iniziare
Prima di creare un volume da uno snapshot, prendere in considerazione le seguenti limitazioni:

* È possibile ripristinare un volume da uno snapshot solo se si dispone già di una copia snapshot del volume.
* Modifiche ai modelli di autorizzazione: Se si utilizza questa operazione per cambiare il tipo di protocollo NAS (Network-Attached Storage), è possibile che cambi anche il modello di autorizzazione fornito dallo stile di protezione. Potrebbero verificarsi problemi di autorizzazione all'accesso ai file, che è possibile risolvere solo manualmente con l'accesso dell'amministratore utilizzando gli strumenti client NAS per l'impostazione delle autorizzazioni.


.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. In *Archiviazione*, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, selezionare il menu azioni del file system con il volume e quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *volumi*.
. Dalla scheda *Volumi*, selezionare il menu delle azioni per il volume da ripristinare da uno snapshot.
. Selezionare *Azioni di protezione dei dati* e quindi *Gestisci snapshot*.
. Dalla pagina Gestisci snapshot, seleziona il menu delle azioni per lo snapshot da ripristinare, quindi seleziona *Ripristina*.
. Nella finestra di dialogo Ripristina volume da uno snapshot, seleziona una delle seguenti opzioni:
+
** Attiva/disattiva per selezionare *Ripristina come nuovo volume*.
+
Nel campo *nome volume ripristinato*, immettere un nome univoco per il volume da ripristinare.

** Ripristina i dati da uno snapshot a un volume esistente.  Questa operazione elimina definitivamente tutti i dati modificati dopo la creazione dello snapshot.
+
Accettare la dichiarazione per procedere.



. Selezionare *Restore* (Ripristina).

