---
sidebar: sidebar 
permalink: stop-replication.html 
keywords: stop replication, break replication 
summary: Interrompere una relazione di replica tra volumi di origine e di destinazione in NetApp Workload Factory. 
---
= Interrompere una relazione di replica in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Interrompere una relazione di replica in NetApp Workload Factory.  Quando si interrompe una relazione di replica, gli aggiornamenti di replica pianificati dal volume di origine al volume di destinazione vengono sospesi.  Il volume di destinazione passa da sola lettura a lettura/scrittura.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Relazioni di replica*.
. Nella scheda Relazioni di replicazione, selezionare il menu delle azioni della relazione di replicazione da interrompere.
. Selezionare *Pausa*.
. Nella finestra di dialogo Interrompi replica, selezionare *Interrompi*.


.Risultato
Lo stato di replica del volume cambia in *rotto*. Il volume di destinazione diventa scrivibile.
