---
sidebar: sidebar 
permalink: stop-replication.html 
keywords: stop replication, break replication 
summary: Interruzione di una relazione di replica tra i volumi di origine e di destinazione. 
---
= Interruzione di una relazione di replica
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Quando si interrompe una replica, vengono pianificati gli aggiornamenti della replica dal volume di origine alla pausa del volume di destinazione. Il volume di destinazione passa da sola lettura a lettura-scrittura.

.Fasi
. Accedere alla console workload Factory.
. Nella memoria di archiviazione, selezionare *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, fare clic sul menu dei tre punti del file system da aggiornare, quindi selezionare *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Relazioni di replica*.
. Nella scheda Relazioni di replica, fare clic sul menu dei tre punti della relazione di replica da arrestare.
. Selezionare *Pausa*.
. Nella finestra di dialogo Interrompi replica, selezionare *Interrompi*.


Lo stato di replica del volume cambia in *rotto*. Il volume di destinazione diventa scrivibile.
