---
sidebar: sidebar 
permalink: update-backup-schedule.html 
keywords: backup schedule, backup policy, update backups, update backup schedule, FSx for ONTAP backup 
summary: Aggiorna la pianificazione di backup di FSX per ONTAP quando necessario. 
---
= Aggiorna la pianificazione del backup di FSX per ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aggiorna la pianificazione di backup di FSX per ONTAP quando necessario.

.Fasi
. Accedere a. link:https://console.workloads.netapp.com/["Console di workload Factory"^]
. In archiviazione, fare clic su *Vai all'inventario di archiviazione*.
. Nella scheda *FSX per ONTAP*, fare clic sul menu a tre punti del file system per aggiornare la pianificazione di backup per, quindi selezionare *Gestisci*.
. In informazioni, fare clic sull'icona a forma di matita accanto a *FSX per il backup di ONTAP*. L'icona a forma di matita viene visualizzata accanto alla freccia del menu a discesa quando il mouse passa sopra la riga *FSX per il backup di ONTAP*.
. Nella finestra di dialogo *FSX per il backup di ONTAP*, fornire quanto segue:
+
.. *Backup automatici giornalieri*: Consente di attivare o disattivare la funzione. Se si disattiva la funzione, fare clic su *Applica*. Se si attiva la funzione, completare la procedura riportata di seguito.
.. *Periodo conservazione backup automatico*: Immettere il numero di giorni per la conservazione dei backup automatici.
.. *Finestra di backup automatico giornaliero*: Selezionare *Nessuna preferenza* (l'ora di inizio del backup giornaliero è selezionata per l'utente) o *selezionare l'ora di inizio per i backup giornalieri* e specificare l'ora di inizio.
.. *Finestra manutenzione settimanale*: Selezionare *Nessuna preferenza* (l'ora di inizio della finestra di manutenzione settimanale è selezionata) o *selezionare l'ora di inizio per la finestra manutenzione settimanale di 30 minuti* e specificare un'ora di inizio.


. Fare clic su *Apply* (Applica).

