---
sidebar: sidebar 
permalink: update-throughput-capacity.html 
keywords: update throughput, change throughput, throughput capacity 
summary: Aggiornare la capacità di elaborazione per un file system FSx for ONTAP in NetApp Workload Factory secondo necessità. 
---
= Aggiornare la capacità di throughput per un file system
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aggiornare la capacità di elaborazione per un file system FSx for ONTAP in NetApp Workload Factory secondo necessità.

Per i limiti di capacità di throughput, fai riferimento alla link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Quote"^] documentazione di AWS FSX per NetApp ONTAP.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system per cui aggiornare la capacità di throughput, quindi seleziona *Gestisci*.
. In informazioni, selezionare l'icona a forma di matita accanto a *capacità di trasmissione*. L'icona a forma di matita viene visualizzata accanto alla freccia del menu a discesa quando il mouse passa sopra la riga *capacità di throughput*.
. Nella finestra di dialogo capacità di throughput, selezionare la capacità di throughput desiderata.
. Selezionare *Applica* per salvare le modifiche.

