---
sidebar: sidebar 
permalink: update-snapshot-replication.html 
keywords: update snapshot data, replication 
summary: Aggiorna manualmente i dati dello snapshot trasferiti tra i volumi di origine e di destinazione in una relazione di replica in qualsiasi momento. 
---
= Aggiornare i dati dello snapshot in una relazione di replica
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Una relazione di replicazione ha una pianificazione di replicazione impostata, ma è possibile aggiornare manualmente i dati snapshot trasferiti tra i volumi di origine e di destinazione in NetApp Workload Factory in qualsiasi momento.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Dal menu Archiviazione, selezionare *FSx per ONTAP*.
. Da *FSx for ONTAP*, seleziona il menu delle azioni del file system da aggiornare, quindi seleziona *Gestisci*.
. Nella panoramica del file system, selezionare la scheda *Relazioni di replica*.
. Nella scheda Relazioni di replicazione, selezionare il menu delle azioni della relazione di replicazione da aggiornare.
. Selezionare *Aggiorna ora*.
. Nella finestra di dialogo Aggiorna, selezionare *Aggiorna ora*.

