---
sidebar: sidebar 
permalink: view-volume-details.html 
keywords: volume details, volume information 
summary: Visualizza dettagli sui volumi, distribuzione, consumo, accesso e protezione. 
---
= Visualizza i dettagli del volume in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Visualizza dettagli sui volumi, distribuzione, consumo, accesso e protezione.

I dettagli del volume vengono visualizzati solo dopo la creazione di un volume in un file system.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Archiviazione, seleziona *Vai ad Archiviazione*.
. Nella scheda Volumi, seleziona il menu azioni per il volume che desideri modificare.
. Selezionare *azioni di base*, quindi *Visualizza dettagli volume*.
. In *Dettagli volume*, selezionare le schede per visualizzare i seguenti dettagli del volume:
+
.. *Dettagli generali*: Include nome del volume, UUID del volume, ID del volume, tempo di creazione, stato, tipo di volume (lettura/scrittura/protezione dati (RW/DP) o sola lettura), nome della policy di snapshot, VM di storage host (SVM) e tag.
.. *Distribuzione*: Include gli aggregati di hosting, lo stile del volume (FlexGroup o FlexVol), gli elementi costitutivi (solo FlexGroup) e il rapporto di ribilanciamento (solo FlexGroup -high, medium o low).
.. *Consumo*: Include dimensioni, SSD utilizzati, pool di capacità utilizzato, impostazione crescita automatica, dimensioni max della crescita, impostazione dell'efficienza dello storage, risparmio dello spazio di compressione, risparmio dello spazio di deduplica, policy di tiering e giorni di raffreddamento.
.. *Access*: Include percorso di giunzione, stile di sicurezza, policy di esportazione e versione NFS per NFS, e Active Directory, nome di condivisione CIFS, utenti o gruppi e autorizzazioni per SMB/CIFS, gruppo iniziatore e host IQN per iSCSI.
.. *Protezione*: Include l'istantanea locale, il nome del criterio snapshot, la replica remota e il backup di FSX per ONTAP.



