---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx' 
summary: Scopri le novità di Amazon FSX per NetApp ONTAP. 
---
= Novità
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità di Amazon FSX per NetApp ONTAP.



== 4 agosto 2024



=== Supporto terraforme

Ora puoi utilizzare Terraform di Codebox per distribuire e gestire file system e macchine virtuali di storage.

* link:create-file-system.html["Creare un file system"]
* link:create-storage-vm.html["Creare una VM di storage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilizzare Terraform da Codebox"^]




=== Consigli su throughput e IOPS nel calcolatore dello storage

Il calcolatore dello storage formula raccomandazioni di configurazione del file system FSX per ONTAP per il throughput e gli IOPS sulla base delle Best practice di AWS, il che ti fornisce una guida ottimale per le tue scelte.



== 7 luglio 2024



=== Release iniziale di workload Factory per i database

La release iniziale include la capacità di esplorare i risparmi con Amazon FSX per NetApp ONTAP come ambiente di storage per i carichi di lavoro del database, rilevare, gestire e implementare server Microsoft SQL, implementare e clonare database e monitorare questi job all'interno di workload Factory.
