---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx for netapp ontap, fsx for ontap' 
summary: Scopri le novità di Amazon FSX per NetApp ONTAP. 
---
= Novità
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità di Amazon FSX per NetApp ONTAP.



== 1 settembre 2024



=== Supporto della modalità di lettura per la gestione dello storage

La modalità di lettura è disponibile per la gestione dello storage in workload Factory. La modalità di lettura migliora l'esperienza della modalità di base aggiungendo autorizzazioni di sola lettura in modo che i modelli Infrastructure-as-Code vengano riempiti con variabili specifiche. I modelli Infrastructure-as-Code possono essere eseguiti direttamente dal tuo account AWS senza fornire autorizzazioni di modifica a workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Ulteriori informazioni sulla modalità di lettura"^]



=== Backup prima del supporto per l'eliminazione del volume

È ora possibile eseguire il backup di un volume prima di eliminarlo. Il backup rimarrà nel file system fino all'eliminazione.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["Eliminare un volume"^]



== 4 agosto 2024



=== Supporto terraforme

Ora puoi utilizzare Terraform di Codebox per implementare file system e macchine virtuali di storage.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Creare un file system"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Creare una VM di storage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilizzare Terraform da Codebox"^]




=== Consigli su throughput e IOPS nel calcolatore dello storage

Il calcolatore dello storage formula raccomandazioni di configurazione del file system FSX per ONTAP per il throughput e gli IOPS sulla base delle Best practice di AWS, il che ti fornisce una guida ottimale per le tue scelte.



== 7 luglio 2024



=== Release iniziale di workload Factory per Amazon FSX per NetApp ONTAP

Amazon FSX per NetApp ONTAP è ora generalmente disponibile in workload Factory.
