---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx' 
summary: Scopri le novità di Amazon FSX per NetApp ONTAP. 
---
= Novità
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità di Amazon FSX per NetApp ONTAP.



== 4 agosto



=== Supporto terraforme

Ora puoi utilizzare Terraform di Codebox per distribuire e gestire file system e macchine virtuali di storage.

* link:create-file-system.html["Creare un file system"]
* link:create-storage-vm.html["Creare una VM di storage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilizzare Terraform da Codebox"^]




=== Consigli su throughput e IOPS nel calcolatore dello storage

Il calcolatore dello storage formula raccomandazioni di configurazione del file system FSX per ONTAP per il throughput e gli IOPS sulla base delle Best practice di AWS, il che ti fornisce una guida ottimale per le tue scelte.



== 7 luglio

Amazon FSX per NetApp ONTAP è ora generalmente disponibile in BlueXP workload Factory.

link:learn-fsx-ontap.html["Scopri BlueXP workload Factory per Amazon FSX per NetApp ONTAP"].
